export type JobTask={id:string;title:string;description:string;stage:string;required:boolean;evidenceRequired:boolean;completedAtUtc:string|null;notes:string;evidenceIds:string[]};
export type JobRequirement={id:string;kind:string;description:string;quantity:number;unit:string;status:string;notes:string};
export type JobIssue={id:string;type:string;severity:string;description:string;resolvedAtUtc:string|null;resolution:string};
export type JobChange={id:string;description:string;status:string;pricingImpact:boolean;scopeImpact:string;scheduleImpact:string;customerApproval:string};
export type JobExecution={origin:string;tradeProfile:string;serviceType:string;soldScope:string;ownerMembershipId:string|null;tradeData:Record<string,string>;profile:{fields:Record<string,string>;stateLabels:Record<string,string>;customerAcceptanceRequired:boolean};tasks:JobTask[];requirements:JobRequirement[];issues:JobIssue[];changes:JobChange[];evidence:{id:string;name:string;contentType:string}[];acceptances:{id:string;signer:string;statement:string;exceptions:string;acceptedAtUtc:string}[]};
export type JobRow={id:string;name:string;customerName:string;jobSiteName:string;state:string;stateLabel?:string;trade:string;nextAction:string;blockers:number;atRisk?:boolean;modern:boolean;assignedToMe?:boolean;scheduledStart:string|null;scheduledEnd:string|null;ownerMembershipId:string|null;crew:string|null};
export type JobDetail={job:{id:string;version:string;name:string;customerName:string;jobSiteName:string;jobSiteId?:string|null;projectAddress:string;contactPhone:string;leadId:string|null;estimateId:string|null;description:string;scheduledStart:string|null;execution:JobExecution|null;acceptedEstimate:{selectedOptions?:{name:string;lines:{name:string;quantity:number;unit:string}[]}[];revision:number;source:string;referral:string;document:{scope:string;terms:string;commitments:string;inputs?:Record<string,{value:number;confirmed:boolean}>;attachments:{id:string;name:string}[]}}|null;activity:{id:string;type:string;label:string;note:string;occurredAtUtc:string;actor:string}[]};state:string;stateLabel:string;nextAction:string;scheduleBlockers:string[];startBlockers:string[];completionBlockers:string[];transitions:string[];events:{id:string;title:string;startUtc:string;endUtc:string;eventStatus:string;membershipIds:string[];resourceIds:string[];jobEventType:string;customerVisible:boolean}[];canWrite:boolean};
export type JobNotification={receiptId:string;channel:string;template:string;status:string;message:string;createdAtUtc:string};
export type JobsPage={notifications?:JobNotification[];fieldView:boolean;choices:{customers:{id:string;name:string}[];sites:{id:string;name:string;address:string}[];members:{id:string;name:string;team?:string}[]};workspace:{jobs:JobRow[];canWrite:boolean;canConfigure:boolean;configuration:{allowManual:boolean;enabledTrades:string[]}};selected:JobDetail|null;basePath:string};
export const jobLabel=(state:string)=>state.replaceAll('_',' ').toLowerCase().replace(/^./,s=>s.toUpperCase());
export function visibleJobs(jobs:JobRow[],view:string,now=new Date()){
 const date=now.toLocaleDateString();return jobs.filter(j=>view==='all'||view==='attention'&&(j.atRisk||j.blockers>0||['BLOCKED','WAITING','COMPLETION_REVIEW','COMPLETED'].includes(j.state))||view==='today'&&(j.state==='IN_PROGRESS'||!!j.scheduledStart&&new Date(j.scheduledStart).toLocaleDateString()===date)||view==='upcoming'&&!!j.scheduledStart&&new Date(j.scheduledStart)>now||view==='schedule'&&!!j.scheduledStart).sort((a,b)=>(a.scheduledStart??'9999').localeCompare(b.scheduledStart??'9999'));
}
