export type SupplyItem={id:string;name:string;description:string;kind:string;unit:string;stocked:boolean;jobSpecific:boolean;sku:string;active:boolean;trades:string[];defaultCost:number|null};
export type SupplyDemand={id:string;jobId:string;jobName:string;requirementId:string;description:string;itemId:string|null;quantity:number;unit:string;strategy:string;trade:string;requiredAtUtc:string|null;gate:string;overrideReason:string;readiness:{status:string;required:number;reserved:number;received:number;consumed:number;shortage:number;reasons:string[]}};
export type SupplyOrder={id:string;number:string;vendorId:string;status:string;expectedAtUtc:string|null;locationId:string|null;vendorReference:string;dispatchStatus?:string|null;files?:{id:string;name:string;contentType:string}[];approvalReasons:string[];total:number|null;lines:{id:string;demandId:string;description:string;quantity:number;unit:string;unitCost:number|null;received:number;directToJob:boolean}[]};
export type SupplyWorkspace={version:string;canWrite:boolean;canInventoryWrite:boolean;canPurchase:boolean;canPurchaseWrite:boolean;canConfigure:boolean;catalog:SupplyItem[];locations:{id:string;name:string;type:string}[];demands:SupplyDemand[];balances:{itemId:string;locationId:string;onHand:number;reserved:number;available:number}[];movements?:{id:string;itemId:string;type:string;quantity:number;unit:string;fromLocationId:string|null;toLocationId:string|null;jobId:string|null;reason:string;atUtc:string;actor:string}[];reservations:{id:string;demandId:string;itemId:string;locationId:string;quantity:number;status:string}[];vendors:{contactId:string;name:string;preferred:boolean}[]|null;vendorChoices:{id:string;name:string}[];jobChoices:{id:string;name:string;requirements:{id:string;description:string;quantity:number;unit:string;catalogItemId:string|null}[]}[];orders:SupplyOrder[];requests:{id:string;demandId:string;quantity:number;status:string;reason:string}[]|null;receipts:{id:string;orderId:string;lineId:string;accepted:number;damaged:number;atUtc:string;reference:string;files:{id:string;name:string;contentType:string}[]}[];suggestions:{demandId:string;options:{vendorId:string;leadDays:number;preferred:boolean;cost:number|null;canMeetDate:boolean|null;explanation:string}[]}[];policy:SupplyPolicy|null;tradeProfiles?:SupplyPolicy['trades'];units:string[];metrics:{shortages:number;lateOrders:number;receivedByUnit?:{unit:string;accepted:number;damaged:number}[];orderValue:number|null}};
export type SupplyPage={workspace:SupplyWorkspace;module:'inventory'|'purchasing';basePath:string;jobId:string|null};
export const orderTransitions=(state:string):string[]=>({DRAFT:['PENDING_APPROVAL','APPROVED','CANCELLED'],PENDING_APPROVAL:['APPROVED','CANCELLED'],APPROVED:['PENDING_APPROVAL','SENT','CANCELLED'],SENT:['ACKNOWLEDGED','CANCELLED'],ACKNOWLEDGED:['CANCELLED'],RECEIVED:['CLOSED']} as Record<string,string[]>)[state]||[];
export const label=(value:string)=>value.toLowerCase().replaceAll('_',' ').replace(/^./,v=>v.toUpperCase());
export const orderInView=(o:SupplyOrder,view:string,now=Date.now())=>view==='All orders'||view==='Waiting'&&['SENT','PENDING_APPROVAL','DRAFT','APPROVED'].includes(o.status)||view==='Incoming'&&['SENT','ACKNOWLEDGED','PARTIALLY_RECEIVED'].includes(o.status)||view==='Receiving'&&['SENT','ACKNOWLEDGED','PARTIALLY_RECEIVED'].includes(o.status)||view==='Late'&&!!o.expectedAtUtc&&Date.parse(o.expectedAtUtc)<now&&!['RECEIVED','CLOSED','CANCELLED'].includes(o.status);

export type SupplyPolicy={approvalAbove:number;nonPreferredApproval:boolean;rushApproval:boolean;priceOverrideApproval:boolean;spendingLimits:Record<string,number>;aiActions:Record<string,string>;trades:Record<string,{defaultStrategy:string;gate:string;preferredUnits:string[];fields:string[];deliveryRequired:boolean}>};
