<script lang="ts">
 import {enhance} from '$app/forms';import type {SubmitFunction} from '@sveltejs/kit';import {onMount} from 'svelte';import {Package,ShoppingCart,AlertTriangle,CheckCircle2,Truck} from 'lucide-svelte';
 import {label,orderInView,orderTransitions,type SupplyPage,type SupplyDemand} from '$lib/supply';
 let {data,form}: {data:SupplyPage;form?:{message?:string;failed?:boolean}|null}=$props();
 let view=$state(''),search=$state(''),busy=$state(false),online=$state(true),mounted=$state(false),selectedJob=$state(''),selectedTrade=$state('');
 const s=$derived(data.workspace),buying=$derived(data.module==='purchasing');const current=$derived(view||(buying?'To buy':'Needs attention'));
 const views=$derived(buying?['To buy','Waiting','Incoming','Late','Receiving','All orders']:['Needs attention','Job demand','Receiving','Locations','Item search','All items']);
 const demands=$derived(s.demands.filter(d=>(!data.jobId||d.jobId===data.jobId)&&(!search||`${d.description} ${d.jobName}`.toLowerCase().includes(search.toLowerCase()))&&(current==='Job demand'||d.readiness.shortage>0)));
 const disabled=$derived(!mounted||busy||!online);const itemName=(id:string)=>s.catalog.find(i=>i.id===id)?.name||id;const locationName=(id:string)=>s.locations.find(l=>l.id===id)?.name||'Job site';
 const date=(v:string|null)=>v?new Date(v).toLocaleString():'Not confirmed';
 const submit:SubmitFunction=({cancel})=>{if(!online||busy){cancel();return;}busy=true;return async({update})=>{try{await update();}finally{busy=false;}};};
 onMount(()=>{mounted=true;online=navigator.onLine;if('serviceWorker'in navigator)void navigator.serviceWorker.register('/supply-service-worker.js',{scope:`${data.basePath}/${data.module}`}).catch(()=>{});const update=()=>online=navigator.onLine;window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};});
</script>
{#snippet identity(action:string,targetId='')}<input type="hidden" name="version" value={s.version}/><input type="hidden" name="action" value={action}/><input type="hidden" name="targetId" value={targetId}/>{/snippet}
{#snippet locations(name='locationId',optional=false)}<select {name} required={!optional}><option value="">{optional?'Direct to Job / service':'Choose location'}</option>{#each s.locations as l}<option value={l.id}>{l.name} · {l.type}</option>{/each}</select>{/snippet}
{#snippet units(value='each')}<select name="unit" {value}>{#each s.units as u}<option>{u}</option>{/each}</select>{/snippet}
{#snippet request(d:SupplyDemand)}
 {#if s.canPurchaseWrite}<details><summary>Request purchasing</summary><form method="POST" action="?/save" use:enhance={submit}>{@render identity('request',d.id)}<label>Quantity<input name="quantity" type="number" min="0.001" step="any" max={d.readiness.shortage} value={d.readiness.shortage} required/></label><label>Urgency<select name="state"><option value="normal">Normal</option><option value="rush">Rush</option></select></label><label>Reason<input name="reason" required/></label><button class="primary" disabled={disabled}>Create purchase request</button></form></details>{/if}
{/snippet}
<svelte:head><link rel="manifest" href={`${data.basePath}/${data.module}/manifest.webmanifest`}/><title>{buying?'Purchasing':'Inventory'} · TurnKeyOps</title></svelte:head>
<div class="supply space-y-6">
 <header><p class="eyebrow">Operational supply</p><h1>{#if buying}<ShoppingCart size={28}/>{:else}<Package size={28}/>{/if}{buying?'Purchasing':'Inventory'}</h1><p class="muted mt-2">{buying?'Source what Jobs need. Track confirmation, arrival and receiving.':'Know what each Job needs, what is available, and what needs attention.'}</p><div class="links">{#if s.canPurchase&&!buying}<a href={`${data.basePath}/purchasing`}>Open purchasing</a>{/if}<a href={`${data.basePath}/jobs`}>Jobs</a>{#if buying}<a href={`${data.basePath}/inventory`}>Inventory</a>{/if}</div></header>
 {#if form?.message}<p role={form.failed?'alert':'status'} class="notice">{form.message}</p>{/if}
 {#if !online}<p role="alert" class="notice">You are offline. No stock or purchasing changes can be submitted. Reconnect and refresh before continuing.</p>{/if}
 <section aria-label="Supply attention" class="metrics"><div><AlertTriangle size={20}/><strong>{s.metrics.shortages}</strong><span>Material shortages</span></div><div><Truck size={20}/><strong>{s.metrics.lateOrders}</strong><span>Late orders</span></div><div><CheckCircle2 size={20}/><strong>{s.receipts.length}</strong><span>Recorded receipts</span></div></section>
 <nav aria-label="Supply views">{#each views as tab}<button disabled={!mounted} class:active={current===tab} aria-pressed={current===tab} onclick={()=>view=tab}>{tab}</button>{/each}</nav>
 <label class="search">Search materials or Jobs<input type="search" bind:value={search} placeholder="Find a material or Job"/></label>
 {#if ['Needs attention','Job demand','To buy'].includes(current)}
  <section aria-label="Job material demand" class="space-y-4">{#each demands as d}<article class="panel">
   <div class="row"><div><p class="eyebrow">{d.jobName} · {d.trade}</p><h2>{d.description}</h2></div><span class="badge">{label(d.readiness.status)}</span></div>
   <p class="mt-3">Needs {d.quantity} {d.unit} · {d.strategy==='stock'?'Stock or purchase':'Direct to Job'} · {date(d.requiredAtUtc)}</p>
   <p class="muted">{d.readiness.reserved} reserved · {d.readiness.received} allocated · {d.readiness.consumed} consumed</p>
   {#if d.readiness.reasons.length}<ul class="reasons">{#each d.readiness.reasons as reason}<li>{reason}</li>{/each}</ul>{/if}
   {#if d.overrideReason}<p>Manager override: {d.overrideReason}</p>{/if}
   {#if s.canConfigure&&s.canInventoryWrite}<details><summary>Manager readiness override</summary><form method="POST" action="?/save" use:enhance={submit}>{@render identity(d.overrideReason?'clear-override':'override',d.id)}{#if !d.overrideReason}<label>Reason for starting without full supply<input name="reason" required/></label>{/if}<button disabled={disabled}>{d.overrideReason?'Remove override':'Record readiness override'}</button></form></details>{/if}
   <a href={`${data.basePath}/jobs/${d.jobId}`}>Open Job</a>
   {#if s.canInventoryWrite}<details><summary>Schedule a delivery</summary><p class="muted">Uses the shared Calendar. Jobs and Calendar write access are required.</p><form method="POST" action="?/save" use:enhance={submit}>{@render identity('schedule-delivery',d.id)}<input type="hidden" name="jobId" value={d.jobId}/><input type="hidden" name="title" value={`Delivery: ${d.description}`}/><label>Delivery start (include time zone)<input name="startUtc" required placeholder="2026-10-12T08:30:00-04:00"/></label><label>Delivery end (include time zone)<input name="endUtc" required placeholder="2026-10-12T09:00:00-04:00"/></label><button disabled={disabled}>Schedule delivery</button></form></details>{/if}
   <details><summary>Availability & sourcing</summary>
    {#each s.balances.filter(b=>b.itemId===d.itemId) as b}<p>{locationName(b.locationId)}: {b.onHand} on hand, {b.reserved} reserved, <strong>{b.available} available</strong>.</p>{:else}<p class="muted">No stock balance for this requirement.</p>{/each}
    {#each s.suggestions.find(v=>v.demandId===d.id)?.options??[] as option}<p class="mt-3">{s.vendors?.find(v=>v.contactId===option.vendorId)?.name||'Supplier'} · {option.leadDays} lead days · {option.canMeetDate===true?'Could meet required date':option.canMeetDate===false?'Lead time risk':'Required date unknown'}{option.cost!==null?` · Recorded cost ${option.cost}`:''}</p><p class="muted">{option.explanation}</p>{/each}
    {#if s.canInventoryWrite&&d.strategy==='stock'&&d.itemId&&d.readiness.shortage>0}<form method="POST" action="?/save" use:enhance={submit}>{@render identity('reserve',d.id)}<input type="hidden" name="unit" value={d.unit}/><label>Reserve from{@render locations()}</label><label>Reserve quantity<input name="quantity" type="number" step="any" min="0.001" max={d.readiness.shortage} value={d.readiness.shortage} required/></label><button class="primary" disabled={disabled}>Reserve stock</button></form>{/if}
   </details>
   {#if !buying}{@render request(d)}{/if}
   {#if buying&&s.canPurchaseWrite&&d.readiness.shortage>0}{@render request(d)}<details><summary>Create purchase order</summary><form method="POST" action="?/save" use:enhance={submit}>{@render identity('draft-order',d.id)}<input type="hidden" name="unit" value={d.unit}/><label>Vendor<select name="vendorId" required><option value="">Choose vendor</option>{#each s.vendors??[] as v}<option value={v.contactId}>{v.name}{v.preferred?' · Preferred':''}</option>{/each}</select></label><label>Approved purchase request<select name="requestId"><option value="">Direct buyer draft</option>{#each s.requests?.filter(r=>r.demandId===d.id&&r.status==='APPROVED')??[] as r}<option value={r.id}>{r.quantity} requested</option>{/each}</select></label><label>Quantity<input name="quantity" type="number" step="any" min="0.001" value={d.readiness.shortage} required/></label><label>Unit cost<input name="cost" type="number" min="0" step="0.01" required/></label><label>Delivery location{@render locations('locationId',true)}</label><label class="check"><input name="directToJob" type="checkbox" checked={d.strategy!=='stock'}/>Deliver directly to Job</label><label>Expected arrival (include time zone)<input name="expectedAtUtc" placeholder="2026-10-12T08:30:00-04:00"/></label><label>Delivery instructions<input name="instructions"/></label><button class="primary" disabled={disabled}>Create PO draft</button></form></details>{/if}
   {#if s.canInventoryWrite}<details><summary>Job allocation & usage</summary>{#each s.reservations.filter(r=>r.demandId===d.id&&r.status==='active') as r}<div class="row"><p>{r.quantity} at {locationName(r.locationId)}</p><form method="POST" action="?/save" use:enhance={submit}>{@render identity('issue',r.id)}<button disabled={disabled}>Issue to Job</button></form><form method="POST" action="?/save" use:enhance={submit}>{@render identity('release',r.id)}<button disabled={disabled}>Release</button></form></div>{/each}
    {#if d.readiness.received>d.readiness.consumed}<form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="version" value={s.version}/><input type="hidden" name="targetId" value={d.id}/><input type="hidden" name="unit" value={d.unit}/><label>Record<select name="action"><option value="consume">Consumption</option><option value="return">Return to stock</option></select></label><label>Quantity used or returned<input name="quantity" type="number" step="any" min="0.001" required/></label><label>Return location{@render locations('locationId',true)}</label><label>Usage note<input name="reason" required/></label><button disabled={disabled}>Record usage</button></form>{/if}</details>{/if}
  </article>{:else}<p class="empty">No materials in this view. Map an existing Job requirement to begin.</p>{/each}</section>
 {/if}
 {#if buying&&current!=='To buy'||!buying&&current==='Receiving'}<section class="space-y-4" aria-label="Purchase orders">{#each s.orders.filter(o=>orderInView(o,current)) as o}<article class="panel"><div class="row"><h2>{o.number}</h2><span class="badge">{label(o.status)}</span></div><p>{s.vendors?.find(v=>v.contactId===o.vendorId)?.name||'Vendor'} · Expected {date(o.expectedAtUtc)}</p>{#if o.total!==null}<p>Order total: {o.total.toFixed(2)}</p>{/if}{#if o.approvalReasons.length}<p class="muted">Approval reasons: {o.approvalReasons.join('; ')}</p>{/if}
   {#if o.dispatchStatus}<p role="status">Vendor send: {o.dispatchStatus==='provider-accepted'?'Accepted by provider; vendor delivery is not confirmed.':o.dispatchStatus==='externally-verified'?'Verified externally by an owner.':'Unconfirmed. Review provider history before taking further action.'}</p>{/if}
   {#if s.canPurchaseWrite&&o.status==='APPROVED'&&!o.dispatchStatus}<form method="POST" action="?/save" use:enhance={submit}>{@render identity('send-order',o.id)}<p>Send this approved order to the vendor’s configured ordering email.</p><button class="primary" disabled={disabled}>Send PO email</button></form>{/if}
   {#each o.lines as l}<div class="line"><h3>{l.description}</h3><p>{l.received} of {l.quantity} {l.unit} received · {l.directToJob?'Direct to Job':locationName(o.locationId||'')}</p>
    {#if s.canInventoryWrite&&['SENT','ACKNOWLEDGED','PARTIALLY_RECEIVED'].includes(o.status)&&l.received<l.quantity}<details><summary>Receive items / confirm service</summary><form method="POST" action="?/save" use:enhance={submit}>{@render identity('receive',l.id)}<input type="hidden" name="unit" value={l.unit}/><input type="hidden" name="locationId" value={o.locationId||''}/><label>Accepted quantity<input name="quantity" type="number" min="0" max={l.quantity-l.received} step="any" required/></label><label>Damaged / rejected quantity<input name="damaged" type="number" min="0" max={l.quantity-l.received} step="any" value="0"/></label><label>Packing slip / service reference<input name="reference" required/></label><label>Receiving notes<input name="reason"/></label><button class="primary" disabled={disabled}>Confirm receipt</button></form></details>{/if}</div>{/each}
   {#if s.canPurchaseWrite&&orderTransitions(o.status).length}<details><summary>Next purchasing step</summary><form method="POST" action="?/save" use:enhance={submit}>{@render identity('order-status',o.id)}<label>Next status<select name="state">{#each orderTransitions(o.status) as state}<option value={state}>{state==='SENT'?'Record sent externally':label(state)}</option>{/each}</select></label><label>Vendor communication reference<input name="reference"/></label><label>Confirmed arrival (include time zone)<input name="expectedAtUtc" placeholder="2026-10-12T08:30:00-04:00"/></label><label>Review note<input name="reason"/></label><button class="primary" disabled={disabled}>Update order</button></form></details>{/if}
   {#if s.canPurchase}<details><summary>Order files</summary>{#each o.files??[] as file}<a href={`${data.basePath}/purchasing/${o.id}/files/${file.id}`}>{file.name}</a>{/each}{#if s.canPurchaseWrite}<form method="POST" action="?/save" enctype="multipart/form-data" use:enhance={submit}>{@render identity('files',o.id)}<input type="hidden" name="fileModule" value="purchasing"/><label>Quote, confirmation, PO PDF or product specification<input name="files" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple required/></label><button disabled={disabled}>Attach order files</button></form>{/if}</details>{/if}
  </article>{:else}<p class="empty">No orders in this view.</p>{/each}</section>{/if}
 {#if !buying&&['Locations','Item search','All items'].includes(current)}<section aria-label="Inventory balances">{#each s.catalog.filter(i=>!search||`${i.name} ${i.sku}`.toLowerCase().includes(search.toLowerCase())) as item}<article class="panel mb-4"><h2>{item.name}</h2><p class="muted">{item.sku} · {item.unit} · {item.jobSpecific?'Job-specific':item.stocked?'Stocked':'Direct purchase / service'}</p>{#each s.balances.filter(b=>b.itemId===item.id) as b}<p class="mt-2">{locationName(b.locationId)} · {b.onHand} on hand · {b.reserved} reserved · {b.available} available</p>{/each}</article>{:else}<p class="empty">No catalog items yet.</p>{/each}</section>{/if}
 {#if s.canInventoryWrite&&!buying}<details class="panel"><summary>Map Job material demand</summary><form method="POST" action="?/save" use:enhance={submit}>{@render identity('demand')}<label>Job<select name="jobId" bind:value={selectedJob} required><option value="">Choose Job</option>{#each s.jobChoices as j}<option value={j.id}>{j.name}</option>{/each}</select></label><label>Material requirement<select name="requirementId" required><option value="">Choose requirement</option>{#each s.jobChoices.find(j=>j.id===selectedJob)?.requirements??[] as r}<option value={r.id}>{r.quantity} {r.unit} · {r.description}</option>{/each}</select></label><label>Catalog mapping<select name="itemId"><option value="">Freeform direct purchase</option>{#each s.catalog as i}<option value={i.id}>{i.name} · {i.unit}</option>{/each}</select></label><label>Sourcing strategy<select name="strategy"><option value="">Use trade default</option><option value="stock">Stock or purchase</option><option value="direct">Direct to Job</option><option value="service">Purchased service</option><option value="rental">Rental</option><option value="manual">Manual decision</option></select></label><button class="primary" disabled={disabled}>Map requirement</button></form></details>
 <details class="panel"><summary>Move or count stock</summary><form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="version" value={s.version}/><label>Stock operation<select name="action"><option value="transfer">Transfer</option><option value="adjust">Count / adjustment</option><option value="scrap">Scrap</option></select></label><label>Item<select name="itemId" required>{#each s.catalog.filter(i=>i.stocked&&!i.jobSpecific) as i}<option value={i.id}>{i.name}</option>{/each}</select></label><label>Source / count location{@render locations()}</label><label>Transfer destination{@render locations('toLocationId',true)}</label><label>Count correction<select name="state"><option value="add">Add quantity</option><option value="remove">Remove quantity</option></select></label><label>Movement quantity<input name="quantity" type="number" step="any" min="0.001" required/></label><label>Movement unit{@render units()}</label><label>Movement reason<input name="reason" required/></label><button class="primary" disabled={disabled}>Record movement</button></form></details>
 <details class="panel"><summary>Catalog & locations</summary><h2>Add catalog item</h2><form method="POST" action="?/save" use:enhance={submit}>{@render identity('catalog')}<label>Item name<input name="name" required/></label><label>SKU / internal code<input name="sku"/></label><label>Item category<select name="kind">{#each ['MATERIAL','PRODUCT','CONSUMABLE','EQUIPMENT_PART','SERVICE','SUBCONTRACT','FEE','RENTAL','OTHER'] as k}<option>{k}</option>{/each}</select></label><label>Base unit{@render units()}</label><label>Trade profile<select name="trade" bind:value={selectedTrade}><option value="">Universal</option>{#each Object.keys(s.tradeProfiles??{}) as t}<option>{t}</option>{/each}</select></label><label class="check"><input name="stocked" type="checkbox" checked/>Track stock</label><label class="check"><input name="jobSpecific" type="checkbox"/>Special order for one Job</label><details><summary>Item details, pack conversions & import source</summary>{#each s.tradeProfiles?.[selectedTrade]?.fields??[] as field}<label>{label(field)}<input name={`meta.${field}`}/></label>{/each}<label>Supplier / source unit<input name="conversionUnit" placeholder="box or the original unit label"/></label><label>Base units in one supplier pack<input name="conversionFactor" type="number" min="0.001" step="any"/></label><p class="muted">For example: one box contains 12 each. Confirm the exact pack size with the supplier.</p><label>Import source system<input name="sourceSystem"/></label><label>Original item ID<input name="externalId"/></label></details><button disabled={disabled}>Add catalog item</button></form><h2 class="mt-6">Add location</h2><form method="POST" action="?/save" use:enhance={submit}>{@render identity('location')}<label>Location name<input name="name" required/></label><label>Location type<select name="type">{#each ['warehouse','shop','yard','truck','trailer','staging','job-site'] as t}<option>{t}</option>{/each}</select></label><label>Address<input name="address"/></label><button disabled={disabled}>Add location</button></form></details>{/if}
 {#if buying&&s.canPurchaseWrite}<details class="panel"><summary>Purchase requests ({s.requests?.filter(r=>r.status==='REQUESTED').length||0} pending)</summary>{#each s.requests??[] as r}<div class="line"><h3>{s.demands.find(d=>d.id===r.demandId)?.description}</h3><p>{r.quantity} · {label(r.status)} · {r.reason}</p>{#if s.canConfigure&&r.status==='REQUESTED'}<form method="POST" action="?/save" use:enhance={submit}>{@render identity('approve-request',r.id)}<button disabled={disabled}>Approve request</button></form>{/if}</div>{/each}</details>
 <details class="panel"><summary>Vendors & supplier items</summary><p class="muted">Vendors use existing Contacts. Add the vendor profile in Contacts first.</p><form method="POST" action="?/save" use:enhance={submit}>{@render identity('vendor')}<label>Vendor contact<select name="contactId" required><option value="">Choose existing vendor</option>{#each s.vendorChoices as v}<option value={v.id}>{v.name}</option>{/each}</select></label><label>Ordering email<input name="orderingEmail" type="email"/></label><label>Lead days<input name="leadDays" type="number" min="0" value="0"/></label><label class="check"><input name="preferred" type="checkbox"/>Preferred vendor</label><label class="check"><input name="delivers" type="checkbox"/>Delivery available</label><button disabled={disabled}>Save vendor profile</button></form><h2 class="mt-6">Supplier item</h2><form method="POST" action="?/save" use:enhance={submit}>{@render identity('offer')}<label>Supplier<select name="vendorId" required>{#each s.vendors??[] as v}<option value={v.contactId}>{v.name}</option>{/each}</select></label><label>Catalog item<select name="itemId" required>{#each s.catalog as i}<option value={i.id}>{i.name}</option>{/each}</select></label><label>Supplier item number<input name="vendorItemNumber"/></label><label>Supplier cost<input name="cost" type="number" min="0" step="0.01" required/></label><label>Supplier unit{@render units()}</label><label>Pack size<input name="packSize" type="number" min="0.001" step="any" value="1"/></label><label>Supplier lead days<input name="leadDays" type="number" min="0" value="0"/></label><button disabled={disabled}>Save supplier item</button></form></details>{/if}
 {#if !buying}<details class="panel"><summary>Inventory movement history</summary>{#each s.movements??[] as m}<div class="line"><p>{label(m.type)} · {itemName(m.itemId)} · {m.quantity} {m.unit}</p><p class="muted">{date(m.atUtc)}{m.fromLocationId?` · From ${locationName(m.fromLocationId)}`:''}{m.toLocationId?` · To ${locationName(m.toLocationId)}`:''}</p><p>{m.reason}</p></div>{:else}<p class="muted">No movements recorded.</p>{/each}</details>{/if}
 <details class="panel"><summary>Bob materials coordinator</summary><p class="muted">Review shortages, reservations, preferred supplier lead times and late orders. Bob follows your access and company action policies.</p><form method="POST" action="?/save" use:enhance={submit}>{@render identity('bob')}<button disabled={disabled}>Ask Bob to review supply</button></form></details>
 <details class="panel"><summary>Receipt history</summary>{#each s.receipts as r}<div class="line"><p>{r.reference} · {r.accepted} accepted · {r.damaged} damaged/rejected · {date(r.atUtc)}</p>{#each r.files as file}<a href={`${data.basePath}/inventory/${r.id}/files/${file.id}`}>{file.name}</a>{/each}{#if s.canInventoryWrite}<details><summary>Attach receipt evidence</summary><form method="POST" action="?/save" enctype="multipart/form-data" use:enhance={submit}>{@render identity('files',r.id)}<input type="hidden" name="fileModule" value="inventory"/><label>Packing slip / receipt photo<input name="files" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple required/></label><button disabled={disabled}>Attach receipt files</button></form></details>{/if}</div>{:else}<p class="muted">No receipts recorded.</p>{/each}</details>
 {#if buying&&s.canConfigure&&s.policy}<details class="panel"><summary>Approval rules & trade profiles</summary><p class="muted">Owner configuration. Changes require unsent orders to be approved again.</p><form method="POST" action="?/save" use:enhance={submit}>{@render identity('policy')}<label>Owner approval above<input name="approvalAbove" type="number" min="0" step="0.01" value={s.policy.approvalAbove} required/></label><label class="check"><input name="nonPreferredApproval" type="checkbox" checked={s.policy.nonPreferredApproval}/>Review non-preferred vendors</label><label class="check"><input name="rushApproval" type="checkbox" checked={s.policy.rushApproval}/>Review rush orders</label><label class="check"><input name="priceOverrideApproval" type="checkbox" checked={s.policy.priceOverrideApproval}/>Review manual / changed prices</label>{#each Object.entries(s.policy.trades) as [trade,profile]}<fieldset><legend>{label(trade)}</legend><label>Material readiness<select name={`gate.${trade}`} value={profile.gate}><option value="blocker">Blocks Job start</option><option value="warning">Warning</option></select></label><label>Default sourcing<select name={`strategy.${trade}`} value={profile.defaultStrategy}>{#each ['stock','direct','service','rental','manual'] as strategy}<option value={strategy}>{label(strategy)}</option>{/each}</select></label><label class="check"><input name={`delivery.${trade}`} type="checkbox" checked={profile.deliveryRequired}/>Require a delivery event for direct supply</label></fieldset>{/each}<details><summary>Bob action policies</summary>{#each ['supply.availability','supply.shortages','supply.sources','supply.purchasing','supply.reserve','supply.request','supply.draft-order','supply.send'] as key}<label>{label(key.replace('supply.',''))}<select name={key} value={s.policy.aiActions[key]||(['supply.reserve','supply.request','supply.draft-order','supply.send'].includes(key)?'approval':'read')}><option value="disabled">Disabled</option><option value="read">Read only</option><option value="approval">Ask for approval</option><option value="auto">Automatic within permissions</option></select></label>{/each}</details><button disabled={disabled}>Save supply rules</button></form></details>{/if}
</div>
<style>
 .supply{max-width:1120px;margin:auto;color:var(--text-strong)}h1{display:flex;gap:.7rem;align-items:center;font-size:1.9rem;font-weight:650}h2{font-size:1.15rem;font-weight:650}h3{font-weight:600}.eyebrow{font-size:.75rem;letter-spacing:.08em;text-transform:uppercase;color:var(--text-muted)}.muted{color:var(--text-muted)}.panel,.notice{border:1px solid var(--border);border-radius:12px;padding:1.25rem;background:var(--surface)}.row,.links{display:flex;gap:1rem;align-items:center;flex-wrap:wrap;justify-content:space-between}.links{justify-content:flex-start;margin-top:1rem}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.metrics>div{display:flex;align-items:center;gap:.7rem;flex-wrap:wrap;padding:1rem;border:1px solid var(--border);border-radius:10px}.metrics strong{font-size:1.5rem}.metrics span{width:100%;color:var(--text-muted)}nav{display:flex;gap:.5rem;flex-wrap:wrap}button,a,summary,input,select{min-height:44px}button{padding:.55rem .9rem;border:1px solid var(--border);border-radius:8px;font-weight:600;cursor:pointer;background:var(--surface)}button.active{background:#115e59;color:#fff;border-color:#115e59}.primary{background:#c2410c;color:white;border-color:#c2410c}button:disabled{opacity:.55;cursor:not-allowed}a{display:inline-flex;align-items:center;text-decoration:underline;text-underline-offset:4px}summary{cursor:pointer;font-weight:600;padding:.7rem 0}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin-top:1rem}form>details,form>button{grid-column:1/-1}form>button{justify-self:start}label{display:flex;flex-direction:column;gap:.4rem;font-size:.875rem;font-weight:550}input,select{width:100%;padding:.65rem .8rem;border:1px solid var(--border);border-radius:7px;color:var(--text-strong);background:var(--surface);font-weight:400}.check{flex-direction:row;align-items:center}.check input{width:20px;min-height:24px}.badge{border:1px solid var(--border);padding:.4rem .7rem;border-radius:20px;font-size:.8rem}.reasons{list-style:disc;padding-left:1.3rem;margin:.75rem 0}.line{padding:1rem 0;border-bottom:1px solid var(--border)}.empty{padding:2.5rem 0;color:var(--text-muted)}:is(button,a,summary,input,select):focus-visible{outline:3px solid #0d9488;outline-offset:3px}.row form{display:block;margin:0}@media(max-width:640px){form{grid-template-columns:1fr}.metrics{gap:.5rem}.metrics>div{padding:.7rem}.metrics span{font-size:.8rem}.panel{padding:1rem}h1{font-size:1.6rem}}
</style>
