<script lang="ts">import {page} from '$app/state';let {data,form}=$props();let p=$derived(data.portal);let slug=$derived(page.url.pathname.split('/')[1]);</script>
<div class="mx-auto max-w-3xl space-y-6 p-5"><h1 class="text-2xl font-semibold">Customer portal</h1><p>Configure the company portal and customer-facing features.</p><a class="underline" href={`/${slug}/portal/login`}>Customer login link</a>{#if form?.message}<p role="status">{form.message}</p>{/if}
<form method="POST" action="?/configure" class="space-y-3"><input type="hidden" name="version" value={p.version}/><label><input type="checkbox" name="enabled" checked={p.configuration.enabled}/> Portal enabled</label><label>Company name<input name="companyName" value={p.configuration.companyName} required maxlength="100"/></label><label>Logo asset path (optional)<input name="logoPath" value={p.configuration.logoPath??''} placeholder="/clientFiles/company-logo.png" maxlength="200"/></label><label>Contact information<textarea name="contactInfo" maxlength="500">{p.configuration.contactInfo}</textarea></label><label>Accent<select name="accent"><option selected={p.configuration.accent==='teal'} value="teal">Teal</option><option selected={p.configuration.accent==='blue'} value="blue">Blue</option><option selected={p.configuration.accent==='violet'} value="violet">Violet</option></select></label>
{#each [{key:'financeEnabled',label:'Customer invoices, balances and receipts'},{key:'financePaymentsEnabled',label:'Configured Stripe invoice payment links'},{key:'selfBookingEnabled',label:'Booking from offered appointment times'},{key:'messagingEnabled',label:'Customer messages'},{key:'uploadEnabled',label:'File uploads'},{key:'customerBobEnabled',label:'Customer Bob guidance'},{key:'changeApprovalEnabled',label:'Change approval'},{key:'completionAcceptanceEnabled',label:'Completion acceptance'}] as item}<label><input type="checkbox" name={item.key} checked={p.configuration[item.key]}/>{item.label}</label>{/each}<button>Save configuration</button></form>
<h2 class="text-xl font-semibold">Customer conversations and sharing</h2><form method="GET" class="space-y-3"><label>Customer<select name="customer" required><option value="">Choose a customer contact</option>{#each p.people as person}<option value={person.customerId} selected={person.customerId===data.customer}>{person.firstName} {person.lastName}</option>{/each}</select></label><button>Open shared work</button></form>
{#if data.workspace}<ul>{#each data.workspace.work as work}<li class="py-2"><a class="underline" href={`?customer=${data.customer}&kind=${work.kind}&id=${work.id}`}>{work.title} · {work.status}</a></li>{/each}</ul>{/if}
{#if data.chosen&&data.detail}<h3 class="font-semibold">{data.chosen.title}</h3>{#each data.messages as m}<p class="border-b py-2">{m.from}: {m.text}{m.file?` · ${m.file.name}`:''}</p>{/each}
<form method="POST" action="?/reply"><input type="hidden" name="customer" value={data.customer}/><input type="hidden" name="kind" value={data.chosen.kind}/><input type="hidden" name="id" value={data.chosen.id}/><label>Customer-visible reply<textarea name="text" required maxlength="4000"></textarea></label><button>Post reply</button></form>
{#if data.sharing}<form method="POST" action="?/share"><input type="hidden" name="id" value={data.chosen.id}/><input type="hidden" name="version" value={data.detail.version}/><input type="hidden" name="action" value="update"/><label>Customer-visible progress update<textarea name="text" required maxlength="4000"></textarea></label><button>Share update</button></form>
{#each data.sharing.files??[] as file}<form method="POST" action="?/share" class="border-b py-3"><input type="hidden" name="id" value={data.chosen.id}/><input type="hidden" name="version" value={data.detail.version}/><input type="hidden" name="action" value="file"/><input type="hidden" name="itemId" value={file.id}/><label><input type="checkbox" name="consent" checked={file.customerVisible}/>Share {file.name} with authorized customers</label><button>Save file visibility</button></form>{/each}
{#each data.sharing.changes??[] as change}<form method="POST" action="?/share" class="border-b py-3"><input type="hidden" name="id" value={data.chosen.id}/><input type="hidden" name="version" value={data.detail.version}/><input type="hidden" name="action" value="change"/><input type="hidden" name="itemId" value={change.id}/><p>{change.description}</p>{#if change.pricingImpact}<label>Issued change proposal ID<input name="changeEstimateId" required/></label>{/if}<label><input type="checkbox" name="consent" checked={change.customerVisible}/>Share this change for customer review</label><button>Save change visibility</button></form>{/each}{/if}
{#if data.chosen.kind!=='lead'}<details><summary>Send a customer notification</summary><form method="POST" action="?/notify" class="space-y-3"><input type="hidden" name="id" value={data.chosen.id}/><input type="hidden" name="kind" value={data.chosen.kind}/><input type="hidden" name="version" value={data.detail.version??data.detail.documentHash}/><label>Recipient<select name="userId">{#each p.people.filter((v:any)=>v.customerId===data.customer) as person}<option value={person.userId}>{person.firstName} {person.lastName}</option>{/each}</select></label><label>Channel<select name="channel"><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Notification<select name="template">{#each Object.entries(p.configuration.notificationTemplates) as [key,text]}<option value={key}>{String(text)}</option>{/each}</select></label><p>Only opted-in, verified contacts with current access can receive a notification.</p><button>Send notification</button></form></details>{/if}
{/if}
<h2 class="text-xl font-semibold">Individual customer access</h2><p>Manage portal access on each customer contact’s profile.</p><a class="underline" href={`/${slug}/admin/${slug==='carlzipf'?'customers':'contact'}`}>Open customer contacts</a>

</div>
<style>label{display:block}input:not([type=checkbox]),textarea,select{display:block;border:1px solid var(--border,#94a3b8);padding:.65rem;min-height:44px;width:100%;background:var(--surface,#fff);color:inherit}button{padding:.7rem 1rem;border:1px solid;border-radius:.3rem;min-height:44px}input[type=checkbox]{width:20px;height:20px;vertical-align:middle;margin-right:.5rem}</style>
