<script lang="ts">
 import { onMount } from 'svelte';
 import { enhance } from '$app/forms';
 import { goto } from '$app/navigation';
 import { ArrowLeft, ArrowRight, Plus, Phone, MapPin, Sparkles, CheckCircle, Clock, Paperclip } from 'lucide-svelte';
 import { leadStages, leadSources, queueFor, stageLabel, type LeadWorkspace, type Lead, type Duplicate } from '$lib/leads';
 let {data, form}: {data:{workspace:LeadWorkspace; selected:Lead|null; duplicates:Duplicate[]; intake:{attachments:{id:string;fileName:string}[];timeline:{id:string;label:string;occurredAtUtc:string}[]}|null; basePath:string}; form?:{success?:boolean;message?:string;createdId?:string;bobActionId?:string|null}|null} = $props();
 let ready = $state(false); onMount(()=>{ready=true; if ('serviceWorker' in navigator) navigator.serviceWorker.register('/leads-service-worker.js',{scope:data.basePath}).catch(()=>{});});
 let view = $state('Queue'); let query = $state(''); let creating = $state(false); let busy = $state(false);
 let creationId = $state(''); let stage = $state('QUALIFYING'); let start = $state(''); let end = $state('');
 const lead = $derived(data.selected); const config = $derived(data.workspace.configuration); const canWrite = $derived(data.workspace.canWrite);
 const filtered = $derived(data.workspace.leads.filter(l => `${l.title} ${l.contactName} ${l.siteAddress}`.toLowerCase().includes(query.toLowerCase())));
 const groups = $derived(view === 'Pipeline' ? leadStages.map(s=>({name:stageLabel(s,config),items:filtered.filter(l=>l.stage===s)})) : ['Needs response','Ready to qualify','Discovery / site visit','Ready to estimate','Waiting on customer','Follow up','Won','Lost'].map(name=>({name,items:filtered.filter(l=>queueFor(l.stage)===name)})));
 const money = (value:number|null) => value == null ? '' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
 const date = (value:string) => new Date(value).toLocaleString();
 const submit = () => {busy=true;return async ({update}: {update:(options?:{reset?:boolean})=>Promise<void>})=>{await update({reset:false});busy=false;if(form?.createdId) {creating=false;await goto(`${data.basePath}/${form.createdId}`);}};};
 const base = $derived(data.basePath.replace('/leads',''));
 const nextStage = (current:string) => ({NEW:'QUALIFYING',NEEDS_RESPONSE:'QUALIFYING',QUALIFYING:'QUALIFIED',QUALIFIED:'DISCOVERY',DISCOVERY:'READY_TO_ESTIMATE',ESTIMATING:'PROPOSAL',PROPOSAL:'FOLLOW_UP',FOLLOW_UP:'WON',LOST:'QUALIFYING'}[current] ?? 'QUALIFYING');
 $effect(()=>{if(lead) stage=nextStage(lead.stage);});
</script>
<svelte:head><link rel="manifest" href={`${data.basePath}/manifest.webmanifest`}/><title>{lead ? lead.title : 'Leads'} · TurnKeyOps</title></svelte:head>
<div class="leads mx-auto max-w-7xl space-y-6 p-4 sm:p-7" aria-busy={busy}>
 {#if form?.message}<p class="notice" role={form.success ? 'status':'alert'}>{form.message}</p>{/if}
 {#if lead}
  <a class="inline-flex items-center gap-2" href={data.basePath}><ArrowLeft size={18}/> All leads</a>
  <header class="flex flex-wrap items-start justify-between gap-4">
   <div class="min-w-0"><p class="eyebrow">{lead.stageLabel} · {lead.source}</p><h1 class="break-words text-2xl font-semibold sm:text-3xl">{lead.title}</h1><p class="mt-2">{lead.contactName} {lead.companyName ? `· ${lead.companyName}`:''}</p><p class="muted mt-1">{lead.ownerName} {lead.estimatedValue != null ? `· ${money(lead.estimatedValue)}`:''}</p></div>
   {#if lead.phone}<a class="secondary" href={`tel:${lead.phone.replace(/[^+\d]/g,'')}`}><Phone size={18}/> Call customer</a>{/if}
  </header>
  <ol class="progress flex flex-wrap gap-2" aria-label="Lead lifecycle">
   {#each ['Intake','Qualification','Discovery','Estimate','Decision','Job'] as name,i}<li class:current={(lead.jobId ? 5 : ['WON','LOST','PROPOSAL','FOLLOW_UP'].includes(lead.stage) ? 4 : ['READY_TO_ESTIMATE','ESTIMATING'].includes(lead.stage) ? 3 : lead.stage === 'DISCOVERY' ? 2 : ['QUALIFYING','QUALIFIED'].includes(lead.stage) ? 1 : 0) === i}>{i+1}. {name}</li>{/each}
  </ol>
  <div class="grid items-start gap-6 lg:grid-cols-[minmax(0,1.6fr)_minmax(260px,1fr)]">
   <div class="space-y-5">
    <section class="panel space-y-4" aria-labelledby="current-task"><p class="eyebrow">Current task</p><h2 id="current-task" class="text-xl font-semibold">{lead.nextAction}</h2>
     {#if lead.followUpAtUtc}<p class="flex items-center gap-2"><Clock size={16}/> Follow up {date(lead.followUpAtUtc)}</p>{/if}
     {#if canWrite}
      {#if lead.stage === 'READY_TO_ESTIMATE' || (lead.stage === 'ESTIMATING' && !lead.estimateId)}
       <form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="estimate"/>{@render identity()}<button class="primary" disabled={busy}>Create estimate draft <ArrowRight size={18}/></button></form>
      {:else if lead.stage === 'WON' && !lead.jobId}
       <form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="job"/>{@render identity()}<p class="muted mb-3">The linked estimate must be approved before job handoff.</p><button class="primary" disabled={busy || !lead.estimateId}>Create linked job <ArrowRight size={18}/></button></form>
      {:else if lead.stage !== 'WON'}
       <form method="POST" action="?/save" use:enhance={submit} class="space-y-3"><input type="hidden" name="action" value="stage"/>{@render identity()}
        <label>Next stage<select name="stage" bind:value={stage}>{#each leadStages.filter(s=>s!==lead.stage) as s}<option value={s}>{stageLabel(s,config)}</option>{/each}</select></label>
        {#if stage === 'WON' || stage === 'LOST'}<label>Outcome reason<select name="reason" required><option value="">Choose reason</option>{#each stage==='WON'?config.wonReasons:config.lostReasons as reason}<option>{reason}</option>{/each}</select></label>{/if}
        <button class="primary" disabled={busy}>{lead.stage==='LOST'?'Reopen lead':'Move forward'} <ArrowRight size={18}/></button>
       </form>
      {/if}
     {:else}<p class="muted">You have read access. A colleague with Leads write access can progress this opportunity.</p>{/if}
    </section>
    <section class="panel space-y-3"><h2 class="text-lg font-semibold">What we know</h2><p class="whitespace-pre-wrap">{lead.requestedWork || 'Scope has not been captured yet.'}</p>{#if lead.siteAddress}<p class="flex items-start gap-2"><MapPin size={18}/>{lead.siteAddress}</p>{/if}<p>{lead.tradeProfile} {lead.service ? `· ${lead.service}`:''}</p>
     {#each lead.fields.filter(f=>f.value && !['requestedWork','siteAddress'].includes(f.key)) as field}<p><strong>{field.label}:</strong> {field.value}</p>{/each}
    </section>
    <section class="panel space-y-3"><h2 class="text-lg font-semibold">What’s missing</h2>{#if lead.missingRequired.length}<p class="muted">Required before qualification and estimate handoff</p><ul class="list-disc space-y-1 pl-5">{#each lead.missingRequired as field}<li>{field}</li>{/each}</ul>{#if canWrite}<form method="POST" action="?/save" use:enhance={submit} class="space-y-3"><input type="hidden" name="action" value="qualify"/>{@render identity()}{#each lead.fields.filter(f=>f.required&&!f.value) as field}<label>{field.label}<input name={field.key==='contact'?'email':['requestedWork','siteAddress'].includes(field.key)?field.key:`q.${field.key}`} type={field.key==='contact'?'email':'text'} required/></label>{/each}<button class="secondary" disabled={busy}>Save qualification</button></form>{/if}{:else}<p class="flex items-center gap-2"><CheckCircle size={18}/> Required qualification is complete.</p>{/if}</section>
    {#if canWrite}<section class="panel"><h2 class="mb-3 text-lg font-semibold">Quick note</h2><form method="POST" action="?/save" use:enhance={submit} class="space-y-3"><input type="hidden" name="action" value="note"/>{@render identity()}<label>Activity<select name="type"><option value="note">Note</option><option value="call">Customer call / first response</option><option value="customer-response">Customer response</option><option value="discovery">Discovery findings</option><option value="task">Task / commitment</option></select></label><label>Note<textarea name="text" required maxlength="4000" rows="3" placeholder="Use your keyboard’s microphone to dictate a note."></textarea></label><button class="secondary" disabled={busy}>Save note</button></form></section>{/if}
    <details class="panel"><summary>Full details & qualification</summary><form method="POST" action="?/save" use:enhance={submit} class="mt-4 space-y-4"><input type="hidden" name="action" value="update"/>{@render identity()}{@render fields(lead)}<div class="grid gap-4 sm:grid-cols-2">{#each lead.fields.filter(f=>!['requestedWork','contact','siteAddress'].includes(f.key)) as field}<label>{field.label}{field.required?' · required':''}<input name={`q.${field.key}`} value={field.value} disabled={!canWrite}/></label>{/each}</div>{#if canWrite}<button class="secondary" disabled={busy}>Save details</button>{/if}</form></details>
    <details class="panel"><summary>Communications</summary>{#if canWrite}<form method="POST" action="?/save" use:enhance={submit} class="mt-4 space-y-3">{@render identity()}<label>Channel<select name="channel"><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Subject<input name="subject" maxlength="200" value={`Regarding ${lead.title}`}/></label><label>Message<textarea name="body" required maxlength="4000" rows="5"></textarea></label><p class="muted">Send delivers this message to the customer’s saved email or phone.</p><div class="flex flex-wrap gap-3"><button class="secondary" name="action" value="draft" disabled={busy}>Save draft</button><button class="primary" name="action" value="send" disabled={busy}>Send to customer</button></div></form>{/if}</details>
    <details class="panel"><summary>Visit & follow-up</summary>{#if canWrite}<form method="POST" action="?/save" use:enhance={submit} class="mt-4 space-y-3"><input type="hidden" name="action" value="schedule"/>{@render identity()}<label>Visit start (your local time)<input type="datetime-local" bind:value={start} required/></label><label>Visit end<input type="datetime-local" bind:value={end} required/></label><input type="hidden" name="startUtc" value={start?new Date(start).toISOString():''}/><input type="hidden" name="endUtc" value={end?new Date(end).toISOString():''}/><button class="secondary" disabled={busy}>Schedule in calendar</button></form>{/if}</details>
    <details class="panel"><summary>Files & photos</summary><ul class="mt-3 space-y-2">{#each data.intake?.attachments ?? [] as file}<li><a class="inline-flex min-h-11 items-center gap-2 underline" href={`${data.basePath}/${lead.id}/files/${file.id}`}><Paperclip size={16}/>{file.fileName}</a></li>{/each}</ul>{#if canWrite}<form method="POST" action="?/save" enctype="multipart/form-data" class="mt-3 space-y-3"><input type="hidden" name="action" value="files"/>{@render identity()}<label>Capture a photo or choose files<input type="file" name="files" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" multiple required/></label><p class="muted">Up to 10 files per upload, 10 MB each.</p><button class="secondary">Upload files</button></form>{/if}</details>
    <details class="panel"><summary>Estimates, job & original intake</summary><div class="mt-3 flex flex-col gap-3">{#if lead.estimateId}<a href={`${base}/estimates?request=${lead.intakeRequestId ?? lead.id}`} class="underline">Open linked estimate · {lead.estimateId.slice(0,8)}</a>{/if}{#if lead.jobId && base.includes('/carlzipf')}<p>Linked job · {lead.jobId}</p>{:else if lead.jobId}<a href={`${base}/jobs?job=${lead.jobId}`} class="underline">Open linked job · {lead.jobId.slice(0,8)}</a>{/if}{#if lead.intakeRequestId}<a href={`${base}/requests?request=${lead.intakeRequestId}`} class="underline">Original intake & retained history</a>{/if}{#if lead.referralName}<p>Referred by {lead.referralName}</p>{/if}{#if !lead.customerId && canWrite}<form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="customer"/>{@render identity()}<button class="secondary" disabled={busy}>Create customer from these details</button><p class="muted mt-2">Review possible matches before creating a separate record.</p></form>{/if}<p class="muted">Opportunity ID: {lead.id}</p></div></details>
   </div>
   <aside class="space-y-5">
    <section class="panel intelligence space-y-3"><h2 class="flex items-center gap-2 text-lg font-semibold"><Sparkles size={20}/> Bob’s next step</h2>{#if form?.bobActionId}<form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="bob-approve"/><input type="hidden" name="bobActionId" value={form.bobActionId}/>{@render identity()}<p>Assign this lead using the tenant’s matching rules and priority order.</p><button class="primary mt-3" disabled={busy}>Approve Bob’s assignment</button></form>{/if}<p>{lead.bobSummary}</p><p class="muted">Deterministic qualification guidance. Actions use your permissions and the tenant’s approval policy.</p>{#if canWrite && config.assignmentMode !== 'manual'}<form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="bob"/>{@render identity()}<button class="secondary" disabled={busy}>Let Bob assign this lead</button></form>{/if}</section>
    {#if data.duplicates.length}<section class="panel space-y-3"><h2 class="text-lg font-semibold">Possible matches</h2><p class="muted">These may be separate opportunities. Nothing has been merged.</p>{#each data.duplicates as match}<div class="border-t border-[var(--shell-border)] pt-3"><p class="font-semibold">{match.name}</p><p class="muted">{match.match}</p>{#if match.kind==='contact' && match.id!==lead.customerId && canWrite}<form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="link"/><input type="hidden" name="customerId" value={match.id}/>{@render identity()}<button class="secondary mt-2" disabled={busy}>Link this contact</button></form>{:else if match.kind==='lead'}<a class="inline-flex min-h-11 items-center underline" href={`${data.basePath}/${match.id}`}>Review opportunity</a>{/if}</div>{/each}</section>{/if}
    <section class="panel"><h2 class="mb-4 text-lg font-semibold">Recent activity</h2>{@render activities(lead.activity.slice(-5).reverse())}{#if lead.activity.length>5}<details class="mt-4"><summary>Full history ({lead.activity.length})</summary>{@render activities(lead.activity.slice(0,-5).reverse())}</details>{/if}</section>
   </aside>
  </div>
 {:else}
  <header class="flex flex-wrap items-center justify-between gap-4"><div><p class="eyebrow">Lead to won</p><h1 class="text-3xl font-semibold">What needs to happen next?</h1><p class="muted mt-2">Move each opportunity forward, one useful action at a time.</p></div>{#if canWrite}<button class="primary" disabled={!ready} onclick={()=>{creating=!creating;creationId=crypto.randomUUID();}} aria-expanded={creating}><Plus size={18}/> New lead</button>{/if}</header>
  {#if creating}<section class="panel"><h2 class="mb-4 text-xl font-semibold">Capture an opportunity</h2><form method="POST" action="?/save" use:enhance={submit} class="space-y-4"><input type="hidden" name="action" value="create"/><input type="hidden" name="creationId" value={creationId}/><div class="grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2">Opportunity name<input name="title" required maxlength="200" placeholder="Parking lot repair at Main Street"/></label><label>Customer / contact name<input name="contactName" required/></label><label>Phone<input name="phone" type="tel"/></label><label>Email<input name="email" type="email"/></label><label>Trade<select name="tradeProfile" value={config.defaultTradeProfile}>{#each config.tradeProfiles as trade}<option value={trade}>{trade}</option>{/each}</select></label><label>Source<select name="source"><option>Manual</option>{#each leadSources.filter(s=>s!=='Manual') as source}<option>{source}</option>{/each}</select></label><label>Referred by (when applicable)<input name="referralName"/></label><label class="sm:col-span-2">Requested work<textarea name="requestedWork" rows="3" placeholder="Describe the work. You can dictate with your device keyboard."></textarea></label></div><details><summary>Site, value & customer record</summary><div class="mt-3 grid gap-4 sm:grid-cols-2"><label>Job site<input name="siteAddress"/></label><label>Approximate value<input type="number" name="estimatedValue" min="0" step="0.01"/></label><label>Company<input name="companyName"/></label><label>Existing customer ID (optional)<input name="customerId"/></label></div><label class="mt-3 flex items-center gap-2"><input type="checkbox" name="createCustomer"/> Create a new customer record (review possible matches after saving)</label></details><button class="primary" disabled={busy}>Create lead</button></form></section>{/if}
  <div class="flex flex-wrap items-end justify-between gap-4"><div class="flex gap-2" role="group" aria-label="Lead view">{#each ['Queue','Pipeline','List'] as item}<button class="secondary" class:active={view===item} aria-pressed={view===item} disabled={!ready} onclick={()=>view=item}>{item}</button>{/each}</div><label class="min-w-0">Find an opportunity<input type="search" bind:value={query} placeholder="Name, customer or location"/></label></div>
  {#if !data.workspace.leads.length}<section class="panel py-12 text-center"><h2 class="text-xl font-semibold">Your next opportunity starts here</h2><p class="muted mt-2">New website intake appears automatically. Capture a phone call or referral with New lead.</p>{#if canWrite}<form method="POST" action="?/save" use:enhance={submit} class="mt-5"><input type="hidden" name="action" value="reconcile"/><button class="secondary" disabled={busy}>Bring existing Requests into Leads</button></form>{/if}</section>
  {:else if !filtered.length}<p role="status">No leads match this search.</p>
  {:else if view==='List'}<div class="panel overflow-x-auto"><table class="w-full text-left"><caption class="sr-only">All opportunities</caption><thead><tr><th>Opportunity</th><th>Stage</th><th>Owner</th><th>Next action</th></tr></thead><tbody>{#each filtered as item}<tr><td><a class="inline-flex min-h-11 items-center underline" href={`${data.basePath}/${item.id}`}>{item.title}</a></td><td>{item.stageLabel}</td><td>{item.ownerName}</td><td>{item.nextAction}</td></tr>{/each}</tbody></table></div>
  {:else}<div class={view==='Pipeline'?'grid gap-5 md:grid-cols-2 xl:grid-cols-3':'space-y-7'}>{#each groups.filter(g=>g.items.length) as group}<section><h2 class="mb-3 text-lg font-semibold">{group.name} <span class="muted">{group.items.length}</span></h2><div class={view==='Queue'?'grid gap-3 md:grid-cols-2 xl:grid-cols-3':'space-y-3'}>{#each group.items as item}<article class="panel flex flex-col gap-3"><div><p class="eyebrow">{item.tradeProfile} · {item.source}</p><h3 class="break-words text-lg font-semibold">{item.title}</h3><p class="muted">{item.contactName}</p></div>{#if item.siteAddress}<p class="flex items-start gap-2 text-sm"><MapPin size={16}/>{item.siteAddress}</p>{/if}<p class="muted text-sm">{item.ownerName} {item.estimatedValue!=null?`· ${money(item.estimatedValue)}`:''}</p><p class="muted text-sm">Updated {date(item.updatedAtUtc)}</p>{#if item.missingRequired.length}<p class="text-sm">{item.missingRequired.length} qualification items missing</p>{/if}<a class="primary mt-auto" href={`${data.basePath}/${item.id}`}>{item.nextAction}<ArrowRight size={17}/></a></article>{/each}</div></section>{/each}</div>{/if}
  {#if canWrite && data.workspace.leads.length}<details class="panel"><summary>Historical intake</summary><p class="muted my-3">Link retained Requests without overwriting existing Leads.</p><form method="POST" action="?/save" use:enhance={submit}><input type="hidden" name="action" value="reconcile"/><button class="secondary" disabled={busy}>Reconcile existing Requests</button></form></details>{/if}
  {#if data.workspace.canConfigure}<a class="inline-flex min-h-11 items-center underline" href={`${data.basePath}/settings`}>Lead workflow settings</a>{/if}
 {/if}
</div>
{#snippet identity()}{#if lead}<input type="hidden" name="id" value={lead.id}/><input type="hidden" name="expectedVersion" value={lead.version}/>{/if}{/snippet}
{#snippet activities(items:Lead['activity'])}<ol class="space-y-4">{#each items as item}<li><p class="whitespace-pre-wrap break-words text-sm">{item.text}</p><p class="muted mt-1 text-xs">{item.actor} · {date(item.occurredAtUtc)}</p></li>{/each}</ol>{/snippet}
{#snippet fields(item:Lead)}
 <fieldset disabled={!canWrite} class="grid gap-4 sm:grid-cols-2">
  <label>Opportunity name<input name="title" value={item.title} required maxlength="200"/></label><label>Contact name<input name="contactName" value={item.contactName}/></label><label>Company<input name="companyName" value={item.companyName}/></label><label>Customer ID<input name="customerId" value={item.customerId??''}/></label>
  <label>Email<input type="email" name="email" value={item.email}/></label><label>Phone<input type="tel" name="phone" value={item.phone}/></label><label class="sm:col-span-2">Job site<input name="siteAddress" value={item.siteAddress}/></label><label class="sm:col-span-2">Requested work<textarea name="requestedWork" rows="3" value={item.requestedWork}></textarea></label>
  <label>Trade<select name="tradeProfile" value={item.tradeProfile}>{#each config.tradeProfiles as trade}<option value={trade}>{trade}</option>{/each}</select></label><label>Service<input name="service" value={item.service}/></label><label>Property type<select name="propertyType" value={item.propertyType}><option value="">Not known</option><option value="residential">Residential</option><option value="commercial">Commercial</option></select></label><label>Source<select name="source" value={item.source}>{#each leadSources as source}<option>{source}</option>{/each}</select></label>
  <label>Primary owner<select name="ownerMembershipId" value={item.ownerMembershipId??''}><option value="">Unassigned</option>{#each data.workspace.members as member}<option value={member.id}>{member.name}</option>{/each}</select></label><label>Approximate value<input name="estimatedValue" type="number" min="0" step="0.01" value={item.estimatedValue??''}/></label><label>Referral name<input name="referralName" value={item.referralName}/></label><label>Referral contact ID<input name="referralContactId" value={item.referralContactId??''}/></label><label class="sm:col-span-2">Next action<input name="nextAction" value={item.nextAction}/></label><label>Follow-up (UTC)<input name="followUpAtUtc" value={item.followUpAtUtc??''} placeholder="2026-10-15T15:00:00Z"/></label>
 </fieldset>
{/snippet}
<style>
 .leads{color:var(--text-strong,#111827);--lead-surface:var(--shell-card,#fff);--lead-muted:var(--text-base,#374151)}
 .panel{padding:1.25rem;border:1px solid var(--shell-border,#d1d5db);border-radius:.75rem;background:var(--lead-surface)}
 .eyebrow{font-size:.75rem;letter-spacing:.06em;text-transform:uppercase;color:var(--lead-muted);margin-bottom:.4rem;font-weight:600}
 .muted{color:var(--lead-muted)}
 .primary,.secondary{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;min-height:44px;padding:.65rem 1rem;border-radius:.5rem;font-size:.9rem;font-weight:600;cursor:pointer}
 .primary{background:#f97316;color:#17212b;border:1px solid #f97316}.primary:hover{background:#fb923c}.secondary{background:var(--lead-surface);border:1px solid var(--shell-border-strong,#9ca3af);color:inherit}.secondary.active{border-color:#0f766e;box-shadow:inset 0 -3px #0f766e}
 label{display:block;font-size:.875rem;font-weight:600}input:not([type=hidden]):not([type=checkbox]),select,textarea{display:block;margin-top:.4rem;width:100%;min-height:44px;border:1px solid var(--shell-border-strong,#9ca3af);border-radius:.4rem;padding:.65rem;background:var(--lead-surface);color:inherit;font-weight:400}input[type=checkbox]{width:20px;height:20px}
 summary{cursor:pointer;min-height:44px;align-content:center;font-weight:600}button:disabled{opacity:.65;cursor:wait}a:focus-visible,button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #0f766e;outline-offset:3px}
 .notice{padding:1rem;border:2px solid #0f766e;border-radius:.5rem;background:var(--lead-surface)}.intelligence{border-top:3px solid #0f766e}.progress li{padding:.4rem .7rem;border-bottom:2px solid var(--shell-border,#d1d5db);font-size:.8rem}.progress .current{border-color:#0f766e;font-weight:700}th,td{padding:.5rem;border-bottom:1px solid var(--shell-border,#d1d5db)}
 :global([data-theme=dark]) .leads,:global(.dark) .leads{--lead-surface:#18252b;--lead-muted:#cbd5e1;--text-strong:#f1f5f9;--shell-border:#475569;--shell-border-strong:#64748b}
</style>
