<script lang="ts">
 import { enhance } from '$app/forms';
 import { leadStages, type LeadWorkspace } from '$lib/leads';
 let {data,form}:{data:{workspace:LeadWorkspace;version:string;basePath:string};form?:{success?:boolean;message?:string}|null}=$props();
 const config=$derived(data.workspace.configuration);
</script>
<div class="mx-auto max-w-3xl space-y-6 p-5 text-[var(--text-strong)]">
 <a href={data.basePath} class="inline-flex min-h-11 items-center underline">← Leads</a><h1 class="text-2xl font-semibold">Lead workflow settings</h1><p>Trade recommendations provide the starting point. Tenant overrides apply without changing canonical reporting stages.</p>
 {#if form?.message}<p role={form.success?'status':'alert'}>{form.message}</p>{/if}
 <form method="POST" action="?/save" use:enhance class="space-y-5"><input type="hidden" name="version" value={data.version}/><fieldset disabled={!data.workspace.canConfigure} class="space-y-5">
 <label>Available trade profiles (comma separated)<input name="tradeProfiles" value={config.tradeProfiles.join(', ')}/></label><label>Default trade profile<input name="defaultTradeProfile" value={config.defaultTradeProfile}/></label>
 <details open><summary>Pipeline terminology</summary><div class="mt-3 grid gap-3 sm:grid-cols-2">{#each leadStages as stage}<label>{stage}<input name={`stage.${stage}`} value={config.stageLabels[stage]||stage.toLowerCase().replaceAll('_',' ')}/></label>{/each}</div></details>
 <details><summary>Qualification requirements</summary><p class="my-3">Recommended fields: concrete dimensions/surface; framing dimensions/structure; land clearing acreage/access; doors & locks opening count/hardware. Override a trade with a JSON object of field keys and labels. An empty object for a trade keeps only platform requirements.</p><label>Trade field overrides<textarea name="requiredFields" rows="8" value={JSON.stringify(config.requiredFields,null,2)}></textarea></label></details>
 <details><summary>Ownership & assignment</summary><label class="mt-3">Assignment policy<select name="assignmentMode" value={config.assignmentMode}><option value="manual">Manual</option><option value="rules">Match rules by priority</option><option value="round-robin">Round robin among matching rules</option><option value="workload">Lowest active workload among matching rules</option></select></label><p class="my-3">Rules specify membershipId, optional trade, service, propertyType, source, territory and priority. Only active employees qualify. No matching rule leaves manual assignment required.</p><label>Assignment rules<textarea name="assignmentRules" rows="8" value={JSON.stringify(config.assignmentRules,null,2)}></textarea></label><ul>{#each data.workspace.members as member}<li class="break-all text-sm">{member.name}: {member.id}</li>{/each}</ul></details>
 <details><summary>Bob action authority</summary><p class="my-3">Authority is limited by the current user’s permissions. Stage/outcome changes require approval until deterministic stage rules are configured. Disabled, recommend and draft modes do not execute mutations.</p><div class="grid gap-3 sm:grid-cols-2">{#each ['lead.summarize','lead.assign','lead.stage','lead.task','lead.estimate','lead.draft','lead.send','lead.schedule'] as key}<label>{key}<select name={key} value={config.aiActions[key]||(key==='lead.summarize'?'read':'approval')}><option value="disabled">Disabled</option><option value="read">Read</option><option value="recommend">Recommend only</option><option value="draft">Draft only</option><option value="approval">Human approval</option><option value="auto">Automatic by policy</option></select></label>{/each}</div></details>
 <details><summary>Outcome reasons & referrals</summary><div class="mt-3 grid gap-3 sm:grid-cols-2"><label>Won reasons (one per line)<textarea name="wonReasons" rows="4" value={config.wonReasons.join('\n')}></textarea></label><label>Lost reasons (one per line)<textarea name="lostReasons" rows="4" value={config.lostReasons.join('\n')}></textarea></label></div><label class="mt-3"><input type="checkbox" name="referralRequired" checked={config.referralRequired}/> Require referral details when source is Referral</label></details>
 <button class="min-h-11 rounded-md bg-orange-500 px-5 font-semibold text-slate-950">Save workflow settings</button>
 </fieldset></form>
</div>
<style>
 label{display:block;font-size:.875rem;font-weight:600}input:not([type=checkbox]):not([type=hidden]),textarea,select{display:block;width:100%;min-height:44px;margin-top:.4rem;padding:.65rem;border:1px solid var(--shell-border-strong,#9ca3af);border-radius:.4rem;background:var(--shell-card,#fff);color:inherit;font-weight:400}summary{min-height:44px;align-content:center;cursor:pointer;font-weight:600}details{border-bottom:1px solid var(--shell-border);padding-bottom:.75rem}:is(button,input,textarea,select,summary,a):focus-visible{outline:3px solid #0f766e;outline-offset:3px}
</style>
