// Browser contract fixture. API service/storage checks run separately; no providers are contacted.
import http from 'node:http';
const jobId='11111111-2222-4333-8444-555555555555',proposalId='22222222-2222-4333-8444-555555555555',eventId='33333333-2222-4333-8444-555555555555',changeId='44444444-2222-4333-8444-555555555555',fileId='55555555-2222-4333-8444-555555555555';
const token='A'.repeat(64);let revoked=false,messages=[],response='',accepted=false,proposalSigned=false;
const config={companyName:'Fixture contractor',contactInfo:'Office · 555-0100',enabled:true,messagingEnabled:true,uploadEnabled:true,customerBobEnabled:true,changeApprovalEnabled:true,completionAcceptanceEnabled:true,selfBookingEnabled:true};
const job=()=>({id:jobId,title:'Your door installation',status:'Finalizing your project',version:'v1',site:'North plant',scope:'Install the approved entry door and hardware.',nextStep:'Review the completed work.',updates:[{id:'u1',text:'Installation is finished.',atUtc:'2026-10-06T12:00:00Z'}],files:[{id:fileId,name:'Completion photo.jpg',contentType:'image/jpeg'}],changes:[{id:changeId,description:'Move the closer',reason:'Customer request',scopeImpact:'Adjust the closer location',scheduleImpact:'No schedule change',pricingImpact:false,status:'APPROVAL_REQUIRED',hash:'change-hash'}],issues:[],completion:{ready:!accepted,hash:'completion-hash',revision:1,statement:'I confirm that I have reviewed the completed scope and shared completion documents and accept this work.',allowQualifiedAcceptance:false,acceptedAtUtc:accepted?'2026-10-07T00:00:00Z':null}});
const proposal=()=>({id:proposalId,serviceSummary:'Entry door proposal',scope:'Install a new entry door.',revisionNumber:3,documentHash:'proposal-hash',customerName:'Fixture customer',siteName:'North plant',status:'sent',expiresAtUtc:'2030-10-31T00:00:00Z',terms:'Due on completion.',exclusions:'Painting is excluded.',timing:'At your agreed appointment.',total:2500,options:[{id:'base',name:'Door and hardware',required:true,total:2500,lines:[{name:'Approved door',quantity:1,unit:'each',unitPrice:2500,total:2500}]}],files:[],signature:proposalSigned?{signerPrintedName:'Avery Customer',signedAtUtc:'2026-10-07T00:00:00Z',revisionNumber:3}:null,consentVersion:'quote-approval-v1',consentText:'By typing my name and selecting this checkbox, I intend to electronically sign and approve this quote revision and its total.'});
http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;let body={};try{body=JSON.parse(raw||'{}')}catch{}const path=new URL(req.url,'http://local').pathname;
 const send=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
 if(path==='/health')return send({ok:true});if(path==='/reset'){revoked=false;messages=[];accepted=false;proposalSigned=false;response='';return send({});}if(path==='/revoke'){revoked=true;return send({});}
 if(path.endsWith('/auth/startotp'))return send({challengeId:'fixture-challenge'});if(path.endsWith('/auth/completeotp'))return send({accessToken:'fixture-identity'});
 if(path==='/api/portal-identity/bdr/session')return send({token,expiresAtUtc:'2030-01-01T00:00:00Z'});
 if(!path.startsWith('/api/portal/bdr')||req.headers['x-portal-session']!==token||revoked)return send({message:'Sign in'},401);
 if(path.endsWith('/logout')){revoked=true;return send({});}
 if(path==='/api/portal/bdr')return send({configuration:config,notificationChannels:[],contexts:['site-one','site-two'],work:[{kind:'job',id:jobId,title:'Your door installation',status:'Finalizing your project',siteId:'site-one'},{kind:'estimate',id:proposalId,title:'Entry door proposal',status:'Ready for review',siteId:'site-two'}],appointments:[{id:eventId,startUtc:'2030-10-08T14:00:00Z',endUtc:'2030-10-08T16:00:00Z',status:'scheduled',response,version:'v1',slots:[]}]});
 if(path.endsWith('/explain'))return send({explanation:'Your project is finalizing. Review the completed scope before signing.'});
 if(path===`/api/portal/bdr/work/job/${jobId}`)return send(job());if(path===`/api/portal/bdr/work/estimate/${proposalId}`)return send(proposal());
 if(path.includes('/messages/')){if(path.endsWith('/files'))return send([]);if(req.method==='POST')messages.push({id:crypto.randomUUID(),from:'Customer',text:body.text,atUtc:new Date().toISOString()});return send(messages);}
 if(path.includes('/files/job/')){res.writeHead(200,{'Content-Type':'image/jpeg','Content-Disposition':'attachment; filename="photo.jpg"'});return res.end(Buffer.from([255,216,255,217]));}
 if(path.includes('/appointments/')){response=body.action;return send({});}
 if(path.includes('/jobs/')){if(body.action==='accept-completion')accepted=true;return send({});}
 if(path.includes('/proposals/')){if(!body.intentToSign||!body.signerPrintedName)return send({message:'Explicit electronic-signature intent and your name are required.'},400);proposalSigned=true;return send({});}
 return send({message:'Unavailable'},404);
}).listen(5598,'127.0.0.1');
