import {error} from '@sveltejs/kit';
import {portalRequest,formText,actionFailure} from '$lib/server/portal';
const context=(event:any)=>{if(!['lead','job','estimate'].includes(event.params.kind)||!/^[a-f0-9-]{36}$/i.test(event.params.id))error(404,'Item unavailable');return `${event.params.kind}/${event.params.id}`;};
export const load=async(event)=>{const ctx=context(event);return {kind:event.params.kind,id:event.params.id,detail:await portalRequest(event,`/work/${ctx}`),messages:await portalRequest(event,`/messages/${ctx}`),home:await portalRequest(event)};};
export const actions={
 message:async(event)=>{try{const f=await event.request.formData();await portalRequest(event,`/messages/${context(event)}`,{method:'POST',body:JSON.stringify({text:formText(f,'text')})});return {message:'Your message has been sent to your contractor.'};}catch(e){return actionFailure(e);}},
 upload:async(event)=>{try{const f=await event.request.formData();await portalRequest(event,`/messages/${context(event)}/files`,{method:'POST',body:f});return {message:'Your file has been uploaded.'};}catch(e){return actionFailure(e);}},
 job:async(event)=>{try{context(event);if(event.params.kind!=='job')error(404);const f=await event.request.formData();await portalRequest(event,`/jobs/${event.params.id}`,{method:'POST',body:JSON.stringify({action:formText(f,'action'),expectedVersion:formText(f,'version'),text:formText(f,'text'),signer:formText(f,'signer'),hash:formText(f,'hash'),itemId:formText(f,'itemId')||null,consent:f.get('consent')==='on'})});return {message:'Your response has been recorded.'};}catch(e){return actionFailure(e);}},
 proposal:async(event)=>{try{context(event);if(event.params.kind!=='estimate')error(404);const f=await event.request.formData();await portalRequest(event,`/proposals/${event.params.id}/${encodeURIComponent(formText(f,'decision'))}`,{method:'POST',body:JSON.stringify({revisionNumber:Number(formText(f,'revision')),documentHash:formText(f,'hash'),signerPrintedName:formText(f,'signer'),intentToSign:f.get('consent')==='on',consentVersion:formText(f,'consentVersion'),responseNote:formText(f,'text'),selectedOptionIds:f.getAll('options').map(String)})});return {message:'Your proposal response has been recorded.'};}catch(e){return actionFailure(e);}},
 explain:async(event)=>{try{const answer=await portalRequest(event,`/work/${context(event)}/explain`,{method:'POST'});return {message:answer.explanation};}catch(e){return actionFailure(e);}}
};
