<script lang="ts">
 import {enhance} from '$app/forms';
 import {onMount} from 'svelte';
 import ProposalPreview from './ProposalPreview.svelte';
 import {money,type EstimatePacket} from '$lib/estimates';
 let {packet,accessToken,proposalBase,form}:{packet:EstimatePacket;accessToken:string;proposalBase:string;form?:{message?:string;approvalError?:string;changeMessage?:string;approved?:boolean;changesRequested?:boolean}|null}=$props();
 let selected=$state<string[]>([]);let submitting=$state(false);let ready=$state(false);onMount(()=>{ready=true;});
 $effect(()=>{selected=packet.acceptedOptionIds?.length?[...packet.acceptedOptionIds]:(packet.pricing?.options.filter(x=>x.required).map(x=>x.id)??[]);});
 const total=$derived((packet.pricing?.options??[]).filter(x=>selected.includes(x.id)).reduce((a,x)=>a+x.total,0));
 const submit=()=>{submitting=true;return async({update}:{update:()=>Promise<void>})=>{try{await update();}finally{submitting=false;}};};
</script>
<svelte:head><title>Proposal · {packet.siteName}</title><meta name="robots" content="noindex,nofollow"/></svelte:head>
<main class="customer-proposal mx-auto max-w-3xl space-y-6 px-4 py-8">
 <ProposalPreview {packet}/>
 {#if packet.document?.attachments.length}<section aria-label="Download proposal attachments"><h2 class="text-lg font-semibold">Review attached files</h2><ul>{#each packet.document.attachments as file}<li><a class="link" href={`${proposalBase}/files/${file.id}?token=${encodeURIComponent(accessToken)}`}>{file.name}</a></li>{/each}</ul></section>{/if}
 <button class="secondary no-print" onclick={()=>window.print()}>Print / save PDF</button>
 {#if form?.message}<p role="status">{form.message}</p>{/if}{#if form?.approvalError}<p role="alert">{form.approvalError}</p>{/if}
 {#if packet.delivery?.status==='sent'&&!packet.outcome}
 <form method="POST" action="?/approve" use:enhance={submit} class="panel no-print"><h2 class="text-xl font-semibold">Choose your scope & approve</h2><fieldset disabled={submitting||!ready} class="mt-4 space-y-4"><legend class="sr-only">Proposal acceptance</legend>
 <input type="hidden" name="accessToken" value={accessToken}/><input type="hidden" name="revisionNumber" value={packet.revisionNumber}/><input type="hidden" name="documentHash" value={packet.documentHash}/><input type="hidden" name="consentVersion" value={packet.approvalConsentVersion}/>
 {#each packet.pricing?.options??[] as option}<label class="check"><input type="checkbox" name="option" value={option.id} checked={selected.includes(option.id)} onclick={(event)=>{if(option.required)event.preventDefault();}} onchange={(event)=>{if(option.required)return;selected=event.currentTarget.checked?[...selected.filter(id=>id!==option.id&&(!option.exclusiveGroup||!packet.pricing?.options.some(x=>x.id===id&&x.exclusiveGroup===option.exclusiveGroup))),option.id]:selected.filter(id=>id!==option.id);}} aria-describedby={option.required?`required-${option.id}`:undefined}/><span>{option.name} · {money(option.total)} {option.exclusiveGroup?`· Choose one: ${option.exclusiveGroup}`:''}{#if option.required}<span id={`required-${option.id}`} class="block text-sm">Required base scope</span>{/if}</span></label>{/each}
 <p class="text-xl font-semibold">Selected total: {money(total)}</p><label>Your full name<input name="signerPrintedName" maxlength="200" autocomplete="name" required/></label><label class="check"><input type="checkbox" name="intentToSign" value="yes" required/><span>{packet.approvalConsentText}</span></label><button class="btn-primary" disabled={submitting||!ready}>Sign & accept selected scope</button>
 </fieldset></form>
 <details class="panel no-print"><summary>Ask for changes or decline</summary><form method="POST" action="?/requestChanges" use:enhance={submit} class="mt-3 space-y-4"><input type="hidden" name="accessToken" value={accessToken}/><input type="hidden" name="revisionNumber" value={packet.revisionNumber}/><input type="hidden" name="documentHash" value={packet.documentHash}/><label>Your question or requested change<textarea name="responseNote" rows="4" required maxlength="2000"></textarea></label><label class="check"><input type="checkbox" name="decline" value="yes"/> Decline this proposal</label><button class="secondary" disabled={submitting||!ready}>Send response</button>{#if form?.changeMessage}<p role="alert">{form.changeMessage}</p>{/if}</form></details>
 {:else}<p role="status">{packet.approvalSignature?'Your signed acceptance is recorded.':packet.outcome==='SUPERSEDED'?'This historical revision has been superseded. Ask the office for the current proposal.':packet.outcome==='DECLINED'?'You declined this revision.':'Your response has been recorded. The office will follow up.'}</p>{/if}
</main>
<style>.customer-proposal{color:var(--text-strong,#17212b);line-height:1.6}.panel{border:1px solid var(--border-color,#cbd5e1);padding:1.25rem;border-radius:.6rem;background:var(--surface,#fff)}label{display:block;font-weight:600}input:not([type=checkbox]):not([type=hidden]),textarea{display:block;width:100%;min-height:44px;padding:.65rem;margin-top:.4rem;border:1px solid var(--border-strong,#94a3b8);border-radius:.4rem;background:var(--surface,#fff);color:inherit}.check{display:flex;gap:.75rem;align-items:center;min-height:44px}.check input{width:20px;height:20px;flex-shrink:0}.btn-primary{min-height:44px;padding:.7rem 1.2rem;background:#f97316;color:#17212b;border-radius:.4rem;font-weight:650}.secondary,.link{display:inline-flex;min-height:44px;align-items:center;padding:.6rem 1rem;border:1px solid var(--border-strong,#94a3b8);border-radius:.4rem}.link{text-decoration:underline}summary{min-height:44px;align-content:center;cursor:pointer}:is(button,a,input,textarea,summary):focus-visible{outline:3px solid #0f766e;outline-offset:3px}@media print{.no-print{display:none}.customer-proposal{max-width:none;color:#111;background:white}}</style>
