<script lang="ts">
 import {enhance} from '$app/forms';
 import type {PricingPolicy} from '$lib/server/estimate-settings';
 let {data,form}:{data:{policy:PricingPolicy;settings:{version:string};basePath:string};form?:{message?:string;failed?:boolean}|null}=$props();
 let policy=$state<PricingPolicy|null>(null);let busy=$state(false);
 $effect(()=>{policy=structuredClone(data.policy);});
</script>
<section class="settings mx-auto max-w-4xl space-y-5 p-5">
 <a class="underline" href={data.basePath}>← Estimates</a><h1 class="text-2xl font-semibold">Catalog & pricing rules</h1><p>Configure real business rates and explicit tax treatment. No example catalog items are enabled automatically.</p>
 {#if form?.message}<p role={form.failed?'alert':'status'}>{form.message}</p>{/if}
 {#if policy}<form method="POST" action="?/save" use:enhance={()=>{busy=true;return async({update})=>{try{await update();}finally{busy=false;}};}}><input type="hidden" name="version" value={data.settings.version}/><input type="hidden" name="policy" value={JSON.stringify(policy)}/><fieldset disabled={busy} class="space-y-5">
 <div class="grid gap-4 sm:grid-cols-2"><label>Company display name<input bind:value={policy.companyName}/></label><label>Public website origin for delivery<input type="url" placeholder="https://your-company.example" bind:value={policy.publicOrigin}/></label><label>Tax (%) — required even if zero<input type="number" min="0" max="100" step=".01" bind:value={policy.taxPercent}/></label><label>Discount authority (%)<input type="number" min="0" max="100" step=".01" bind:value={policy.maxDiscountPercent}/></label><label>Minimum margin (%)<input type="number" min="0" max="100" step=".01" bind:value={policy.minimumMarginPercent}/></label><label>Approval above total ($)<input type="number" min="0" step=".01" bind:value={policy.approvalAboveTotal}/></label><label>Minimum charge ($)<input type="number" min="0" step=".01" bind:value={policy.minimumCharge}/></label><label>Deposit (%)<input type="number" min="0" max="100" step=".01" bind:value={policy.depositPercent}/></label></div>
 <label>Default proposal terms<textarea rows="4" bind:value={policy.terms}></textarea></label><label class="check"><input type="checkbox" bind:checked={policy.allowManualOverrides}/> Allow reviewed project price overrides (office approval still required)</label>
 <section><h2 class="text-xl font-semibold">Product & service catalog</h2><p class="my-3">Prices are sell rates. Internal costs are visible only to owners. Disabled or sample items cannot be priced.</p>
 {#each policy.catalog as item,index}<details class="card" open><summary>{item.name||'New item'}</summary><div class="grid gap-3 sm:grid-cols-2"><label>Stable item ID<input bind:value={item.id} required/></label><label>Item name<input bind:value={item.name} required/></label><label>Trade<select bind:value={item.tradeProfile}>{#each ['general','concrete','framing','land-clearing','doors-locks'] as trade}<option>{trade}</option>{/each}</select></label><label>Kind<select bind:value={item.kind}>{#each ['material','labor','equipment','service','subcontract','fee','allowance'] as kind}<option>{kind}</option>{/each}</select></label><label>Unit<input bind:value={item.unit}/></label><label>Unit sell price ($)<input type="number" min="0" step=".01" bind:value={item.unitPrice}/></label><label>Cost-plus markup (%) — optional<input type="number" min="0" max="1000" step=".01" bind:value={item.markupPercent}/></label><label>Unit cost ($) — optional<input type="number" min="0" step=".01" bind:value={item.unitCost}/></label></div><div class="flex flex-wrap gap-5"><label class="check"><input type="checkbox" bind:checked={item.enabled}/> Enabled</label><label class="check"><input type="checkbox" bind:checked={item.taxable}/> Taxable</label><label class="check"><input type="checkbox" bind:checked={item.sample}/> Sample only</label></div><button type="button" class="underline" onclick={()=>policy?.catalog.splice(index,1)}>Remove item from future pricing</button></details>{/each}
 <button type="button" class="secondary" onclick={()=>policy?.catalog.push({id:crypto.randomUUID(),name:'',kind:'material',unit:'each',tradeProfile:'general',unitPrice:0,unitCost:null,enabled:false,taxable:true,sample:false})}>Add catalog item</button></section>
 <details class="card"><summary>Customer agreements & trade requirements</summary><p>Customer discount keys are customer UUIDs. Price keys use customer UUID:item ID. Additional trade fields extend required numeric inputs. These are reviewed configuration maps.</p><label>Customer discounts<textarea rows="4" value={JSON.stringify(policy.customerDiscounts,null,2)} onchange={(e)=>{try{if(policy)policy.customerDiscounts=JSON.parse(e.currentTarget.value);e.currentTarget.setCustomValidity('');}catch{e.currentTarget.setCustomValidity('Enter valid JSON.');}}}></textarea></label><label>Customer prices<textarea rows="4" value={JSON.stringify(policy.customerPrices,null,2)} onchange={(e)=>{try{if(policy)policy.customerPrices=JSON.parse(e.currentTarget.value);e.currentTarget.setCustomValidity('');}catch{e.currentTarget.setCustomValidity('Enter valid JSON.');}}}></textarea></label><label>Additional required fields by trade<textarea rows="4" value={JSON.stringify(policy.requiredFields,null,2)} onchange={(e)=>{try{if(policy)policy.requiredFields=JSON.parse(e.currentTarget.value);e.currentTarget.setCustomValidity('');}catch{e.currentTarget.setCustomValidity('Enter valid JSON.');}}}></textarea></label></details>
 <details class="card"><summary>Stage terminology</summary><p>Optional labels keyed by canonical states, such as SENT or NEEDS_APPROVAL. Workflow and reporting keep their canonical meanings.</p><label>Stage labels<textarea rows="4" value={JSON.stringify(policy.stageLabels,null,2)} onchange={(e)=>{try{if(policy)policy.stageLabels=JSON.parse(e.currentTarget.value);e.currentTarget.setCustomValidity('');}catch{e.currentTarget.setCustomValidity('Enter valid JSON.');}}}></textarea></label></details>
 <p>Bob authority is managed alongside the <a class="underline" href={data.basePath.replace('/estimates','/leads/settings')}>shared action policies</a>.</p><button class="btn-primary" disabled={busy}>Save pricing configuration</button></fieldset></form>{/if}
</section>
<style>.settings{color:var(--text-strong)}label{display:block;font-size:.875rem;font-weight:600}input:not([type=checkbox]):not([type=hidden]),select,textarea{display:block;width:100%;min-height:44px;padding:.65rem;margin:.4rem 0;border:1px solid var(--border-strong,#9ca3af);border-radius:.4rem;background:var(--surface);color:inherit}.check{display:flex;align-items:center;gap:.5rem;min-height:44px}.card{padding:1rem;margin:.8rem 0;border:1px solid var(--border,#cbd5e1);border-radius:.5rem;background:var(--surface)}summary{min-height:44px;align-content:center;font-weight:600;cursor:pointer}.secondary{min-height:44px;border:1px solid var(--border-strong,#9ca3af);padding:.6rem 1rem;border-radius:.4rem}:is(a,button,input,select,textarea,summary):focus-visible{outline:3px solid var(--teal-text);outline-offset:3px}</style>
