<script lang="ts">
 import {enhance} from '$app/forms';
 import {onMount} from 'svelte';
 import {ArrowLeft,FileText,Plus,Sparkles} from 'lucide-svelte';
 import ProposalPreview from './ProposalPreview.svelte';
 import {money,stateLabel,type EstimateDocument,type EstimatePageData} from '$lib/estimates';
 let {data,form}:{data:EstimatePageData;form?:{message?:string;failed?:boolean;bob?:{id:string;status:string;confirmationRequired:boolean}}|null}=$props();
 let doc=$state<EstimateDocument|null>(null);let discount=$state(0);let busy=$state(false);let preview=$state(false);let ready=$state(false);
 const selected=$derived(data.selected);const packet=$derived(selected?.packet);const base=$derived(data.basePath.replace('/estimates',''));
 $effect(()=>{doc=data.selected?.packet.document?structuredClone(data.selected.packet.document):null;discount=data.selected?.packet.pricing?.discountPercent??0;for(const f of data.selected?.fields??[])if(doc&&!doc.inputs[f.key])doc.inputs[f.key]={value:0,confirmed:false,provenance:'Estimator'};});
 onMount(()=>{ready=true;if('serviceWorker'in navigator)void navigator.serviceWorker.register('/estimates-service-worker.js',{scope:data.basePath}).catch(()=>{});});
 const submit=()=>{busy=true;return async({update}:{update:()=>Promise<void>})=>{try{await update();}finally{busy=false;}};};
 function addItem(index:number){doc?.options[index].items.push({catalogId:selected?.catalog[0]?.id??'',quantity:1,quantityKey:'manual',confirmed:false,overrideReason:''});}
 function addOption(){doc?.options.push({id:crypto.randomUUID(),name:'Optional upgrade',required:false,exclusiveGroup:'',items:[]});}
</script>
<svelte:head><title>Estimates · TurnKeyOps</title><link rel="manifest" crossorigin="use-credentials" href={`${data.basePath}/manifest.webmanifest`}/></svelte:head>
<section class="estimates mx-auto max-w-6xl space-y-5 p-4 pb-12 sm:p-6" aria-label="Estimate workspace">
 {#if form?.message}<p role={form.failed?'alert':'status'} class="notice">{form.message}</p>{/if}
 {#if !packet||!selected}
  <header class="flex flex-wrap items-start justify-between gap-3"><div><p class="eyebrow">Lead → Estimate → Proposal</p><h1>Move the next proposal forward</h1><p class="muted mt-2">Start with qualified work. Carry its scope and customer into estimating.</p></div><a class="btn-primary" href={`${base}/leads`}>Open Leads</a></header>
  <div class="flex flex-wrap gap-5">{#if data.workspace.canConfigure}<a class="link" href={`${data.basePath}/settings`}>Catalog & pricing rules</a>{/if}<a class="link" href={`${data.basePath}/legacy`}>Existing trade estimates</a></div>
  <div class="grid gap-4 sm:grid-cols-2">{#each data.workspace.packets as row}<a class="panel block" href={row.modern?`${data.basePath}/${row.id}`:`${data.basePath}/legacy?request=${row.id}`}><p class="eyebrow">{row.stateLabel||stateLabel(row.state)} · revision {row.revisionNumber}</p><h2 class="mt-2">{row.siteName||row.customerName}</h2><p class="muted">{row.customerName} · {row.trade||'Existing trade workflow'}</p><p class="mt-3 font-semibold">{money(row.total)}</p><span class="link mt-3 inline-flex">Review next task →</span></a>{:else}<div class="panel"><h2>No estimates yet</h2><p class="muted mt-2">Open a qualified Lead and choose Prepare estimate. Customer and scope details carry forward.</p></div>{/each}</div>
 {:else}
  <a class="link inline-flex items-center gap-2" href={data.basePath}><ArrowLeft size={18}/> All estimates</a>
  <header class="flex flex-wrap items-start justify-between gap-4"><div><p class="eyebrow">{selected.stateLabel||stateLabel(selected.state)} · Revision {packet.revisionNumber}</p><h1>{packet.siteName||packet.customerName}</h1><p class="muted mt-2">{packet.customerName} · {packet.document?.tradeProfile} {#if packet.leadId}· <a class="link" href={`${base}/leads/${packet.leadId}`}>Source Lead</a>{/if}</p></div><div><p class="muted">Required scope total</p><p class="text-3xl font-semibold">{money(packet.totals.estimatedTotal)}</p><button class="secondary mt-3" disabled={!ready} onclick={()=>preview=!preview}><FileText size={18}/>{preview?'Close preview':'Preview proposal'}</button></div></header>
  {#if preview}<div class="panel"><ProposalPreview {packet}/></div>{/if}
  <section class="panel task"><p class="eyebrow">Current task</p><h2 class="mt-1">{selected.nextAction}</h2>
   {#if packet.pricing?.blockers.length}<ul class="mt-3 list-disc pl-5">{#each packet.pricing.blockers as blocker}<li>{blocker}</li>{/each}</ul>{/if}
   {#if packet.pricing?.approvalReasons.length}<h3 class="mt-4 font-semibold">Requires human review</h3><ul class="list-disc pl-5">{#each packet.pricing.approvalReasons as reason}<li>{reason}</li>{/each}</ul>{/if}
   <div class="mt-4 flex flex-wrap gap-3">{#if selected.canWrite}
    {#if selected.state==='NEEDS_APPROVAL'&&selected.canApprove}{@render task('approve','Approve pricing exceptions')}{/if}
    {#if selected.state==='READY_TO_SEND'}{@render task('issue','Issue customer proposal')}{/if}
    {#if ['SENT','VIEWED','REVISION_REQUESTED','ACCEPTED','DECLINED','EXPIRED'].includes(selected.state)}{@render task('revision','Create new revision')}{/if}
    {#if selected.state==='ACCEPTED'}{@render task('job','Create / link Job')}{/if}
   {/if}</div>
   {#if packet.approvalSignature}<p class="mt-3">Signed by {packet.approvalSignature.signerPrintedName} · {money(packet.approvalSignature.total)} · revision {packet.approvalSignature.revisionNumber}</p>{/if}
  </section>
  <div class="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]">
   <div class="space-y-5">
    <section class="panel"><h2>What we know</h2><p class="mt-3 whitespace-pre-wrap">{packet.document?.scope||packet.serviceSummary}</p><p class="muted mt-3">Customer and site come from the linked Lead. Notes and extracted measurements remain suggestions until confirmed.</p>{#if packet.document?.attachments.length}<p class="mt-3">Source files: {packet.document.attachments.map(x=>x.name).join(', ')}</p>{/if}</section>
    {#if doc&&selected.canWrite&&!packet.delivery&&!packet.outcome}
    <form method="POST" action="?/save" use:enhance={submit} class="panel space-y-5">
     <input type="hidden" name="action" value="price"/>{@render identity()}<input type="hidden" name="document" value={JSON.stringify(doc)}/>
     <fieldset disabled={busy||!ready} class="space-y-5"><legend class="text-lg font-semibold">Confirm scope & measurements</legend>
      <label>Customer-facing scope<textarea rows="4" bind:value={doc.scope}></textarea></label>
      {#if doc.suggestions.length}<details><summary>Bob’s suggestions — confirm before using</summary>{#each doc.suggestions as suggestion}<div class="mt-3 border-b pb-3"><p><strong>{suggestion.key}</strong>{suggestion.value!=null?`: ${suggestion.value}`:''}</p><p class="whitespace-pre-wrap">{suggestion.text}</p><p class="muted text-sm">{suggestion.provenance}</p>{#if suggestion.value!=null&&doc.inputs[suggestion.key]}<button type="button" class="secondary mt-2" onclick={()=>{if(doc)doc.inputs[suggestion.key]={value:suggestion.value!,confirmed:false,provenance:suggestion.provenance};}}>Use as unconfirmed input</button>{:else if suggestion.key==='scope'}<button type="button" class="secondary mt-2" onclick={()=>{if(doc)doc.scope=suggestion.text;}}>Use as draft scope</button>{/if}</div>{/each}</details>{/if}
      <div class="grid gap-4 sm:grid-cols-2">{#each selected.fields as field}<div><label>{field.label} {field.unit?`(${field.unit})`:''}<input type="number" min="0" step="any" bind:value={doc.inputs[field.key].value}/></label><label class="check"><input type="checkbox" bind:checked={doc.inputs[field.key].confirmed}/> I confirmed {field.label.toLowerCase()}</label></div>{/each}</div>
      <details open><summary>Choose catalog items & options</summary><p class="muted my-3">Required scope is included. Optional upgrades are selected by the customer. Prices come from saved tenant catalogs.</p>
       {#each doc.options as option,index}<section class="option space-y-3"><div class="grid gap-3 sm:grid-cols-2"><label>Option name<input bind:value={option.name}/></label><label class="check"><input type="checkbox" bind:checked={option.required}/> Required scope</label><label>Choose-one group (optional)<input placeholder="e.g. repair-or-replace" bind:value={option.exclusiveGroup}/></label></div><p class="muted text-sm">For alternatives, clear Required and give both options the same group name. The customer must choose one.</p>
        {#each option.items as item,itemIndex}<div class="item space-y-3"><label>Catalog item<select bind:value={item.catalogId}><option value="">Choose an item</option>{#each selected.catalog as catalog}<option value={catalog.id}>{catalog.name} · {money(catalog.unitPrice)}/{catalog.unit}</option>{/each}</select></label><div class="grid gap-3 sm:grid-cols-2"><label>Quantity source<select bind:value={item.quantityKey}><option value="manual">Confirmed quantity</option>{#each selected.fields as field}<option value={field.key}>{field.label}</option>{/each}{#if doc.tradeProfile==='concrete'}<option value="squareFeet">Calculated square feet</option><option value="cubicYards">Calculated cubic yards</option><option value="perimeter">Calculated perimeter</option>{/if}{#if doc.tradeProfile==='framing'}<option value="squareFeet">Calculated wall area</option><option value="studCount">Calculated stud count</option>{/if}</select></label>{#if item.quantityKey==='manual'}<label>Quantity<input type="number" min="0.0001" step="any" bind:value={item.quantity}/></label>{/if}</div>{#if item.quantityKey==='manual'}<label class="check"><input type="checkbox" bind:checked={item.confirmed}/> Quantity confirmed</label>{/if}<details><summary>Project price override</summary><label>Override unit price (optional)<input type="number" min="0" step=".01" bind:value={item.overridePrice}/></label><label>Reason<input bind:value={item.overrideReason}/></label><p class="muted">Requires tenant permission and office approval.</p></details><button type="button" class="link" onclick={()=>option.items.splice(itemIndex,1)}>Remove item</button></div>{/each}
        <button type="button" class="secondary" onclick={()=>addItem(index)}><Plus size={16}/> Add catalog item</button>{#if index>0}<button type="button" class="link ml-3" onclick={()=>doc?.options.splice(index,1)}>Remove option</button>{/if}
       </section>{/each}
       <button type="button" class="secondary mt-3" onclick={addOption}>Add an optional upgrade</button>
      </details>
      <details><summary>Terms, exclusions & timing</summary><label>Terms<textarea rows="4" bind:value={doc.terms}></textarea></label><label>Exclusions<textarea rows="3" bind:value={doc.exclusions}></textarea></label><label>Timing / commitments<input bind:value={doc.timing}/></label><div class="grid gap-3 sm:grid-cols-2"><label>Valid for (days)<input type="number" min="1" max="365" bind:value={doc.validDays}/></label><label>Deposit (%)<input type="number" min="0" max="100" bind:value={doc.depositPercent}/></label></div></details>
      <label>Requested discount (%)<input type="number" min="0" max="100" step=".01" name="discount" bind:value={discount}/></label><p class="muted">The server applies customer agreements and checks discount authority.</p>
      <button class="btn-primary" disabled={busy}>Save & calculate authoritative price</button>
     </fieldset>
    </form>{/if}
    {#if selected.canWrite&&!packet.delivery}<details class="panel"><summary>Capture photos & files</summary><p class="muted my-3">Photos stay linked to the source intake. Issued proposals preserve their own exact attachment snapshot.</p><form method="POST" action="?/save" enctype="multipart/form-data" use:enhance={submit}>{@render identity()}<input type="hidden" name="action" value="files"/><label>Site photos or documents<input type="file" name="files" accept="image/*,application/pdf" multiple required/></label><button class="secondary mt-3" disabled={busy}>Upload scope files</button></form></details>{/if}
    {#if packet.pricing}<section class="panel"><h2>Price buildup</h2>{#each packet.pricing.options as option}<details class="mt-3"><summary>{option.name} · {money(option.total)} {option.required?'· Required':'· Optional'}</summary><ul class="space-y-3 py-3">{#each option.lines as line}<li><strong>{line.name}</strong><p>{line.quantity} {line.unit} × {money(line.unitPrice)} = {money(line.total)}</p><p class="muted text-sm">{line.rule}</p></li>{/each}</ul><p>Subtotal {money(option.subtotal)} · discount {money(option.discount)} · tax {money(option.tax)}</p>{#if selected.canViewCosts&&option.cost!=null}<p class="muted">Internal cost {money(option.cost)} · margin {option.marginPercent??'Unknown'}%</p>{/if}</details>{/each}<p class="muted mt-3 break-all text-xs">Pricing rule snapshot {packet.pricing.ruleVersion}</p></section>{/if}
   </div>
   <aside class="space-y-5">
    {#if selected.canWrite}<section class="panel"><h2 class="flex items-center gap-2"><Sparkles size={20}/> Bob estimating assistant</h2><p class="muted my-3">Structure field notes into suggestions. No extracted quantity or price is confirmed automatically.</p><form method="POST" action="?/save" use:enhance={submit}>{@render identity()}<input type="hidden" name="action" value="bob"/><input type="hidden" name="tool" value="estimate.extract"/><label>Field notes<textarea name="text" rows="5" placeholder="20 by 60, 4-inch concrete. Remove asphalt; broom finish." required></textarea></label><button class="secondary mt-3" disabled={busy||!!packet.delivery}>Ask Bob to structure notes</button></form>{#if form?.bob?.confirmationRequired}<form class="mt-3" method="POST" action="?/save" use:enhance={submit}>{@render identity()}<input type="hidden" name="action" value="approve-bob"/><input type="hidden" name="actionId" value={form.bob.id}/><p>Tenant policy requires approval for this action.</p><button class="btn-primary mt-2" disabled={busy}>Approve Bob action</button></form>{/if}</section>{/if}
    {#if packet.delivery}<section class="panel"><h2>Customer proposal</h2><a class="link mt-3 block" href={packet.delivery.reviewUrl}>Open exact issued revision</a><p class="muted text-sm">This private link grants customer review access. Issuing it does not send a message.</p>{#if selected.canWrite&&['SENT','VIEWED'].includes(selected.state)}<form class="mt-4" method="POST" action="?/save" use:enhance={submit}>{@render identity()}<input type="hidden" name="action" value="deliver"/><label>Delivery channel<select name="channel"><option value="email">Email · {packet.delivery.email}</option><option value="sms">SMS · {packet.delivery.phone}</option></select></label><label>Message<textarea name="text" rows="3" required>Please review the attached proposal link and let us know if you have questions.</textarea></label><button class="btn-primary mt-3" disabled={busy}>Send proposal / reminder</button></form>{/if}</section>{/if}
    <details class="panel"><summary>Revision history</summary>{#each packet.revisionHistory as revision}<details class="my-3"><summary>Revision {revision.revisionNumber}</summary><p>{revision.document?.scope}</p>{#each revision.pricing?.options??[] as option}<p>{option.name}: {money(option.total)}</p>{/each}<p class="muted break-all text-xs">{revision.documentHash}</p></details>{:else}<p class="muted">This is the first revision.</p>{/each}</details>
    <details class="panel" open><summary>Activity</summary><ol class="mt-3 space-y-4">{#each [...packet.events].reverse() as event}<li><p>{event.text}</p><p class="muted text-xs">{event.actor} · revision {event.revision} · {new Date(event.atUtc).toLocaleString()}</p></li>{/each}</ol></details>
    {#if selected.canWrite&&!packet.approvalSignature}<details class="panel"><summary>Withdraw proposal</summary><p class="muted my-3">Keep the document and revoke customer access.</p>{@render task('void','Void this estimate')}</details>{/if}
   </aside>
  </div>
 {/if}
</section>
{#snippet identity()}<input type="hidden" name="id" value={packet?.id}/><input type="hidden" name="version" value={packet?.version}/>{/snippet}
{#snippet task(action:string,label:string)}<form method="POST" action="?/save" use:enhance={submit}>{@render identity()}<input type="hidden" name="action" value={action}/><button class="btn-primary" disabled={busy||!ready}>{label}</button></form>{/snippet}
<style>
 .estimates{color:var(--text-strong)}h1{font-size:clamp(1.6rem,3vw,2.2rem);font-weight:650;line-height:1.2}h2{font-size:1.15rem;font-weight:650}.eyebrow{font-size:.78rem;font-weight:650;letter-spacing:.05em;text-transform:uppercase;color:var(--teal-text)}.muted{color:var(--text-muted)}.panel{padding:1.25rem;border:1px solid var(--border);border-radius:.6rem;background:var(--surface)}.task{border-left:4px solid var(--teal-text)}.notice{padding:1rem;border:1px solid var(--border);background:var(--surface)}.link{min-height:44px;align-content:center;text-decoration:underline;text-underline-offset:3px}label{display:block;font-size:.875rem;font-weight:600}input:not([type=checkbox]):not([type=hidden]),select,textarea{display:block;width:100%;margin-top:.4rem;padding:.65rem;min-height:44px;border:1px solid var(--border-strong);border-radius:.4rem;color:var(--text-strong);background:var(--surface);font-weight:400}.check{display:flex;align-items:center;gap:.6rem;min-height:44px}.check input{width:18px;height:18px}.secondary{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;min-height:44px;padding:.6rem .9rem;border:1px solid var(--border-strong);border-radius:.4rem;background:var(--surface)}summary{min-height:44px;align-content:center;cursor:pointer;font-weight:600}.option{border:1px solid var(--border);border-radius:.4rem;padding:1rem;margin-top:1rem}.item{border-top:1px solid var(--border);padding-top:1rem}.btn-primary{min-height:44px}:is(button,a,input,select,textarea,summary):focus-visible{outline:3px solid var(--teal-text);outline-offset:3px}button:disabled{opacity:.55}fieldset{min-width:0}details{min-width:0}
</style>
