<script lang="ts">
 import { untrack } from 'svelte';
 import type { PageData, ActionData } from './$types';
 let { data, form }: { data: PageData; form: ActionData } = $props();
 let content = $state(untrack(() => structuredClone(data.content)));
 const label = (key: string) => key.replaceAll('_', ' ');
</script>
<div class="editor"><h1>Carl Zipf website</h1><p>Edit homepage content, imagery, industry cards, process steps and search metadata. Only Carl Zipf’s content is saved.</p><p><a href="/carlzipf/public">Preview commercial</a> · <a href="/carlzipf/public/residential">Preview residential</a></p>
{#if form?.error}<p role="alert">{form.error}</p>{/if}{#if form?.saved}<p role="status">Website content saved.</p>{/if}
<form method="POST">
 <input type="hidden" name="version" value={form?.version ?? data.version} /><input type="hidden" name="content" value={JSON.stringify(content)} />
 <details open><summary>Commercial homepage copy</summary>{#each Object.keys(content.text) as key}<label>{label(key)}<textarea rows="2" maxlength="5000" bind:value={content.text[key as keyof typeof content.text]}></textarea></label>{/each}</details>
 <details><summary>Commercial CTA targets</summary>{#each Object.keys(content.links) as key}<label>{key}<input bind:value={content.links[key as keyof typeof content.links]} required /></label>{/each}<p>Residential promotion links always lead to the residential homepage.</p></details>
 <details><summary>Commercial imagery</summary><label>Concept imagery disclosure<textarea required bind:value={content.imageryNote}></textarea></label>{#each Object.keys(content.images) as key}<label>{label(key)} image path<input bind:value={content.images[key as keyof typeof content.images]} pattern="/[^/].*" required /></label>{/each}<p>Use existing public asset paths. Images must be approved for use; avoid embedding important copy in images.</p></details>
 {#each ['industries', 'process', 'serviceDrafts'] as section}<details><summary>{section === 'industries' ? 'Industry solutions' : section === 'process' ? 'Project process' : 'Unpublished service page drafts'}</summary>{#each content[section as 'industries' | 'process' | 'serviceDrafts'] as item, i}<fieldset><legend>Card {i + 1}</legend><label>Title<input bind:value={item.title} /></label><label>Description<textarea bind:value={item.description}></textarea></label><button type="button" class="secondary" onclick={() => content[section as 'industries' | 'process' | 'serviceDrafts'].splice(i, 1)}>Remove card</button></fieldset>{/each}<button type="button" class="secondary" onclick={() => content[section as 'industries' | 'process' | 'serviceDrafts'].push({ title: '', description: '' })}>Add card</button></details>{/each}
 <details><summary>Residential homepage copy</summary><p>The existing layout, images and forms are retained. These fields edit its visible wording.</p>{#each Object.keys(content.residentialText) as key}<label>Residential copy {key.replace('copy_', '')}<textarea rows="2" maxlength="5000" bind:value={content.residentialText[key as keyof typeof content.residentialText]}></textarea></label>{/each}</details>
 {#each ['commercialSeo','residentialSeo'] as key}<details><summary>{key === 'commercialSeo' ? 'Commercial search metadata' : 'Residential search metadata'}</summary><label>SEO title<input required bind:value={content[key as 'commercialSeo' | 'residentialSeo'].title} /></label><label>Meta description<textarea required bind:value={content[key as 'commercialSeo' | 'residentialSeo'].description}></textarea></label></details>{/each}
 <button>Save website content</button>
</form></div>
<style>.editor{padding:32px;max-width:1100px;color:#172b23;background:white}label{display:block;font-size:14px;text-transform:capitalize;margin:14px 0}input,textarea{box-sizing:border-box;display:block;width:100%;font:inherit;margin:6px 0;padding:10px;border:1px solid #aab9b0;border-radius:4px}button{padding:12px 20px;background:#213a32;color:white;border:0;border-radius:4px;cursor:pointer}.secondary{background:#edf1ee;color:#213a32}a{text-decoration:underline}details{padding:18px 0;border-top:1px solid #d3ddd6}summary{font-weight:700;cursor:pointer}fieldset{margin:16px 0;border:1px solid #d3ddd6;padding:16px}input:focus-visible,textarea:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid #698267;outline-offset:3px}</style>
