import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';
const id='11111111-2222-4333-8444-555555555555';
const token=[{alg:'fixture'},{role:'owner',tenant_id:'7d40ea6c-313f-4f53-bf7d-5d1ecb9cc50b',exp:4102444800,email:'fixture@example.invalid'}].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.')+'.fixture';
test.beforeEach(async({page,request})=>{await request.post('http://127.0.0.1:5498/reset');await page.context().addCookies([{name:'tko_auth_token',value:token,domain:'127.0.0.1',path:'/'}]);});
for(const theme of ['light','dark'])test(`Field workflow ${theme}: keyboard, checklist, issue, change and axe`,async({page})=>{
 await page.addInitScript(t=>localStorage.setItem('tko-admin-theme',t),theme);await page.goto('/bdr/admin/jobs');await page.getByRole('button',{name:'Today',exact:true}).click();
 await page.getByRole('link',{name:/Fixture installation/}).focus();await page.keyboard.press('Enter');
 await expect(page.getByRole('heading',{name:'Fixture installation'})).toBeVisible();await expect(page.locator('.admin-theme')).toHaveAttribute('data-theme',theme);
 await expect(page.getByText('Install the customer-approved door and hardware.')).toBeVisible();
 await page.getByRole('button',{name:'Complete Verify operation',exact:true}).click();await expect(page.getByText('Completed',{exact:true})).toBeVisible();
 await page.getByLabel('Work performed, progress or observations').fill('Door installed and tested.');await page.getByRole('button',{name:'Record update'}).click();await expect(page.getByRole('status')).toContainText('Job updated');
 await page.getByText('Issues & blockers (0 open)',{exact:true}).click();await page.getByLabel('Issue',{exact:true}).fill('Access needs customer confirmation');await page.getByRole('button',{name:'Report issue'}).click();await expect(page.getByRole('heading',{name:'Access needs customer confirmation'})).toBeVisible();
 await page.getByText('Scope changes (0)',{exact:true}).click();await page.getByLabel('Requested change').fill('Customer requested another opening');await page.getByRole('button',{name:'Capture change request'}).click();await expect(page.getByRole('heading',{name:'Customer requested another opening'})).toBeVisible();
 const axe=await new AxeBuilder({page}).include('.jobs').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);expect(await page.locator('.jobs').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();await page.screenshot({path:`test-results/jobs-${theme}-${test.info().project.name}.png`,fullPage:true});
});
test('Jobs read-only view offers no mutations',async({page,request})=>{await request.post('http://127.0.0.1:5498/scenario',{data:{readOnly:true}});await page.goto(`/bdr/admin/jobs/${id}`);await expect(page.getByRole('heading',{name:'Approved scope'})).toBeVisible();for(const name of ['Continue Job','Record update','Report issue','Upload evidence'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);});
test('Completion acceptance captures a separate statement',async({page,request})=>{await request.post('http://127.0.0.1:5498/scenario',{data:{completed:true}});await page.goto(`/bdr/admin/jobs/${id}`);await page.getByLabel('Customer / signer').fill('Fixture customer');await page.getByLabel('Signature / confirmation').fill('Fixture customer');await page.getByRole('button',{name:'Record customer acceptance'}).click();await expect(page.getByText(/Fixture customer ·/)).toBeVisible();});
test('Job rules use labeled touch controls',async({page})=>{await page.goto('/bdr/admin/jobs/settings');await page.getByRole('button',{name:'Customize this trade profile'}).click();await expect(page.getByLabel('Required completion photos')).toBeVisible();const axe=await new AxeBuilder({page}).include('.settings').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);});
test('Offline recovery never claims successful sync or caches records',async({page,context})=>{await page.goto('/bdr/admin/jobs');await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise<void>(r=>navigator.serviceWorker.addEventListener('controllerchange',()=>r(),{once:true}));});const paths=await page.evaluate(async()=>{return(await Promise.all((await caches.keys()).map(async n=>(await(await caches.open(n)).keys()).map(r=>new URL(r.url).pathname)))).flat();});expect(paths).toEqual(['/jobs/offline.html']);await context.setOffline(true);await page.reload();await expect(page.getByRole('heading')).toContainText('offline');await expect(page.getByText(/No Job changes have been submitted/)).toBeVisible();await context.setOffline(false);});
test('All tenant manifests are public and Job pages stay protected',async({request})=>{for(const tenant of ['bdr','carlzipf','thinkpink']){const r=await request.get(`/${tenant}/admin/jobs/manifest.webmanifest`);expect(r.status()).toBe(200);expect(r.headers()['set-cookie']).toBeUndefined();}expect((await request.get('/bdr/admin/jobs',{headers:{Accept:'application/json'}})).status()).toBe(401);});

test('Notification uncertainty remains explicit in the Job workspace',async({page})=>{
 await page.goto('/bdr/admin/jobs/11111111-2222-4333-8444-555555555555');
 await page.getByText('Customer notification receipts',{exact:true}).click();
 await expect(page.getByText('Delivery unconfirmed. Review provider history before requesting another notification.',{exact:true})).toBeVisible();
});
