// Browser contract fixture only. No fixture values are used by production Finance.
const job='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',vendor='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',invoice='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const accounts=[['1000','Operating cash','ASSET','DEBIT'],['1100','Accounts receivable','ASSET','DEBIT'],['2000','Accounts payable','LIABILITY','CREDIT'],['2100','Sales tax payable','LIABILITY','CREDIT'],['3000','Opening equity','EQUITY','CREDIT'],['4000','Contract revenue','REVENUE','CREDIT'],['5000','Direct job costs','COST_OF_GOODS_SOLD','DEBIT']].map(([code,name,type,normalBalance])=>({code,name,type,normalBalance,systemControlled:true,active:true}));
let version=1,drafts=[];
export function resetFinanceFixture(){version=1;drafts=[];}
export function financeFixture(input){
 if(input){if(input.expectedVersion!==String(version))return{error:'Finance changed',status:409};if(input.action==='draft-journal')drafts.push({id:crypto.randomUUID(),date:input.date,memo:input.reason,lines:input.lines});version++;return{data:{saved:true}};}
 return{canWrite:true,canControl:true,jobChoices:[{id:job,name:'Miller Residence'}],vendors:[{id:vendor,name:'Stone supplier'}],orders:[],state:{version:String(version),accounts,periods:[{id:'2026-09',start:'2026-09-01',end:'2026-09-30',status:'OPEN'}],journals:[{id:'journal-one',date:'2026-09-15',sourceType:'invoice',sourceId:invoice,memo:'INV-100',postedBy:'owner',postedAtUtc:'2026-09-15T12:00:00Z',lines:[{account:'1100',debit:1100,credit:0},{account:'4000',debit:0,credit:1000},{account:'2100',debit:0,credit:100}]}],journalDrafts:drafts,openItems:[{id:invoice,kind:'AR',partyId:vendor,number:'INV-100',date:'2026-09-15',dueDate:'2026-09-30',total:1100,journalId:'journal-one',jobId:job}],settlements:[],bills:[{id:'bill-one',vendorId:vendor,number:'BILL-1',date:'2026-09-15',dueDate:'2026-10-15',total:400,status:'PENDING_APPROVAL',matchExceptions:['Missing or insufficient receipt.']}],cashAccounts:[{id:'operating',name:'Operating cash',ledgerAccount:'1000',institution:'',maskedReference:''}],bankTransactions:[{id:'bank-one',date:'2026-09-15',cashAccountId:'operating',amount:100,reference:'Deposit',externalId:'statement:1'}],reconciliations:[],costCodes:[{code:'MATERIAL',name:'Material',category:'MATERIAL'}],costs:[],audit:[],policy:{matching:'warning',accounts:{cash:'1000',ar:'1100',ap:'2000',tax:'2100',equity:'3000',revenue:'4000',cost:'5000'},currency:'USD',materialActualSource:'vendor-bill',revenueRecognition:'invoice'}},reports:{from:'2026-09-01',asOf:'2026-10-07',ar:1100,ap:0,arDifference:0,apDifference:0,trialDifference:0,profit:1000,balanceSheet:{assets:1100,liabilities:100,equity:1000,currentEarnings:1000,difference:0},trialBalance:accounts.map(a=>({...a,debit:a.code==='1100'?1100:0,credit:a.code==='4000'?1000:a.code==='2100'?100:0,balance:a.code==='1100'?1100:a.code==='4000'?-1000:a.code==='2100'?-100:0})),incomeStatement:[{code:'4000',name:'Contract revenue',type:'REVENUE',amount:1000},{code:'5000',name:'Direct job costs',type:'COST_OF_GOODS_SOLD',amount:0}],aging:[{id:invoice,kind:'AR',number:'INV-100',partyId:vendor,jobId:job,dueDate:'2026-09-30',balance:1100,daysPastDue:7,bucket:'1–30'}],cash:[{id:'operating',name:'Operating cash',balance:0}]},jobs:[{jobId:job,contractValue:1000,approvedChanges:0,currentValue:1000,budget:{MATERIAL:400,LABOR:null},committed:400,actual:0,revenue:1000,grossProfit:null,grossMargin:null,costDataIncomplete:true,completenessNote:'Cost data incomplete',categories:[],sourceIds:[]}],close:[{id:'2026-09',issues:['Unposted vendor bills require review.']}],suggestions:[{id:'bank-one',candidates:[]}]};
}
