trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - release-*

pr: none

extends:
  template: templates/static-web-app-deploy.yml
  parameters:
    environmentName: 'Production'
    appDirectory: 'admin'
    artifactName: 'bdr-admin'
    deploymentToken: '$(BDR_ADMIN_STATIC_WEB_APP_TOKEN)'
    deployBranch: '__tag_only__'
    deployTagPrefix: 'release-'
    requireManualApproval: true
