trigger:
  branches:
    include:
    - main
  paths:
    include:
    - admin/*
    - api/.azure-pipelines/bdr-admin.yml
    - api/.azure-pipelines/templates/static-web-app-deploy.yml

pr:
  branches:
    include:
    - main
  paths:
    include:
    - admin/*
    - api/.azure-pipelines/bdr-admin.yml
    - api/.azure-pipelines/templates/static-web-app-deploy.yml

extends:
  template: templates/static-web-app-deploy.yml
  parameters:
    environmentName: 'Production'
    appDirectory: 'admin'
    artifactName: 'bdr-admin'
    deploymentToken: '$(BDR_ADMIN_STATIC_WEB_APP_TOKEN)'
    deployBranch: 'main'
