trigger:
  branches:
    include:
    - develop
    - development

pr: none

extends:
  template: templates/api-deploy.yml
  parameters:
    environmentName: 'Development'
    buildConfiguration: 'Debug'
    webAppName: 'dev-medinsights-api'
    azureSubscription: 'Qurvia / MedInsights Development'
    resourceGroupName: 'development'
    deployBranchPrimary: 'develop'
    deployBranchSecondary: 'development'
