trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - release-*
pr: none

extends:
  template: templates/api-deploy.yml
  parameters:
    environmentName: 'Production'
    buildConfiguration: 'Release'
    webAppName: '$(TURNKEYOPS_API_WEB_APP_NAME)'
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
    resourceGroupName: '$(TURNKEYOPS_PRODUCTION_RESOURCE_GROUP)'
    deployBranchPrimary: '__tag_only__'
    deployTagPrefix: 'release-'
    requireManualApproval: true
    smokeApiBaseUrl: '$(TURNKEYOPS_API_BASE_URL)'
    smokeWebBaseUrl: '$(TURNKEYOPS_WEB_BASE_URL)'
