trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - api/**
    - nuget.config

pr: none

extends:
  template: templates/api-deploy.yml
  parameters:
    environmentName: 'Staging'
    buildConfiguration: 'Release'
    webAppName: '$(TURNKEYOPS_STAGING_API_WEB_APP_NAME)'
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
    resourceGroupName: '$(TURNKEYOPS_STAGING_RESOURCE_GROUP)'
    deployBranchPrimary: 'main'

