trigger:
  branches:
    include:
    - main
  paths:
    include:
    - client/*
    - api/.azure-pipelines/turnkeyops-web.yml
    - api/.azure-pipelines/templates/node-app-service-deploy.yml

pr:
  branches:
    include:
    - main
  paths:
    include:
    - client/*
    - api/.azure-pipelines/turnkeyops-web.yml
    - api/.azure-pipelines/templates/node-app-service-deploy.yml

extends:
  template: templates/node-app-service-deploy.yml
  parameters:
    environmentName: 'Production'
    appDirectory: 'client'
    artifactName: 'turnkeyops-web'
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
    resourceGroupName: '$(TURNKEYOPS_PRODUCTION_RESOURCE_GROUP)'
    webAppName: '$(TURNKEYOPS_WEB_APP_NAME)'
    apiBaseUrl: '$(TURNKEYOPS_API_BASE_URL)'
    deployBranch: 'main'
