import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
for(const tenant of ['carlzipf','bdr','thinkpink']) test(`${tenant}: customer classification persists and residential contact setup is prefilled`,async({page,context,request})=>{
 await request.get('http://127.0.0.1:5190/reset');
 if(tenant==='bdr')await page.setViewportSize({width:393,height:851});
 const tid=tenant==='carlzipf'?'88888888-8888-4888-8888-888888888883':tenant==='bdr'?'7d40ea6c-313f-4f53-bf7d-5d1ecb9cc50b':'88888888-8888-8888-8888-888888888882';
 const token=`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify({sub:'11111111-1111-1111-1111-111111111111',role:['owner'],tid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')}.fixture`;
 await context.addCookies([{name:'tko_auth_token',value:token,url:'http://127.0.0.1:5191'}]);
 const base=`/${tenant}/admin/${tenant==='carlzipf'?'customers':'customer-records'}`, customer='22222222-2222-2222-2222-222222222222';
 await page.goto(`${base}?customer=${customer}`);await page.waitForLoadState('networkidle');
 await expect(page.getByRole('radio',{name:'Residential',exact:true})).not.toBeChecked();
 await expect(page.getByRole('radio',{name:'Commercial',exact:true})).not.toBeChecked();
 await expect(page.getByRole('group',{name:'Customer type',exact:true}).getByRole('button',{name:'Needs classification',exact:true})).toHaveCount(0);
 await page.getByRole('radio',{name:'Residential',exact:true}).check();
 await page.getByRole('button',{name:'Save customer',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Customer saved.');
 await page.reload();
 await expect(page.getByRole('radio',{name:'Residential',exact:true})).toBeChecked();
 await expect(page.getByRole('img',{name:'Residential customer',exact:true})).toBeVisible();
 await expect(page.getByLabel('Portal contact first name',{exact:true})).toHaveValue('Customer');
 await expect(page.getByLabel('Portal login email',{exact:true})).toHaveValue('customer@example.invalid');
 await page.getByRole('button',{name:'Set up portal access',exact:true}).click();
 await expect(page.getByText('Status: Inactive',{exact:true})).toBeVisible();
 const people=await (await request.get('http://127.0.0.1:5190/api/people',{headers:{Authorization:`Bearer ${token}`}})).json();
 expect(people.data.find((p:{customerId?:string})=>p.customerId===customer).role).toBeUndefined();
 await page.getByRole('radio',{name:'Commercial',exact:true}).check();
 await page.getByLabel('Company name',{exact:true}).fill('Acme Facilities');
 await page.getByRole('button',{name:'Save customer',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Customer saved.');await page.reload();
 await expect(page.getByRole('radio',{name:'Commercial',exact:true})).toBeChecked();
 await expect(page.getByRole('img',{name:'Commercial customer',exact:true})).toBeVisible();
 const list=page.getByRole('region',{name:'Customers',exact:true});
 await expect(list.getByRole('heading',{name:'Acme Facilities',exact:true})).toBeVisible();
 await expect(page.getByText('Status: Inactive',{exact:true})).toBeVisible();
 await page.getByRole('group',{name:'Customer type',exact:true}).getByRole('button',{name:'Residential',exact:true}).click();
 await expect(list.getByText('No customers match your search.',{exact:true})).toBeVisible();
 await page.getByRole('group',{name:'Customer type',exact:true}).getByRole('button',{name:'Commercial',exact:true}).click();
 await expect(list.getByRole('heading',{name:'Acme Facilities',exact:true})).toBeVisible();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
