import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('user CRUD persists across reloads with multiple profiles and module permissions',async({page,context,request})=>{
 await request.get('http://127.0.0.1:5190/reset');
 const claims={sub:'11111111-1111-1111-1111-111111111111',role:['owner'],tid:'7d40ea6c-313f-4f53-bf7d-5d1ecb9cc50b',exp:Math.floor(Date.now()/1000)+3600};
 const token=`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.ui-fixture`;
 await context.addCookies([{name:'tko_auth_token',value:token,url:'http://127.0.0.1:5191'}]);
 await page.goto('/bdr/admin/users');
 await page.waitForLoadState('networkidle');
 await expect(page.getByRole('heading',{name:'People & access'})).toBeVisible();
 await page.getByRole('button',{name:'Add user',exact:true}).click();
 await page.getByLabel('First name',{exact:true}).fill('Alex');
 await page.getByLabel('Last name',{exact:true}).fill('Rivera');
 await page.getByLabel('Login email or phone').fill('alex@example.invalid');
 await page.getByLabel('Contact email',{exact:true}).fill('alex-work@example.invalid');
 await page.getByRole('checkbox',{name:'employee',exact:true}).check();
 await page.getByRole('checkbox',{name:'vendor',exact:true}).check();
 await page.getByLabel('Permission policy').selectOption('custom');
 await page.locator('select[name="module:jobs"]').selectOption('read');
 await page.getByRole('button',{name:'Save user',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('User saved.');
 await page.reload();
 await page.waitForLoadState('networkidle');
 await page.getByRole('button',{name:/Alex Rivera/}).click();
 await expect(page.getByRole('checkbox',{name:'employee',exact:true})).toBeChecked();
 await expect(page.getByRole('checkbox',{name:'vendor',exact:true})).toBeChecked();
 await expect(page.locator('select[name="module:jobs"]')).toHaveValue('read');
 await page.getByLabel('First name',{exact:true}).fill('Alexandra');
 await page.getByRole('button',{name:'Save user',exact:true}).click();
 await expect(page.getByRole('button',{name:/Alexandra Rivera/})).toBeVisible();
 await page.reload();
 await page.waitForLoadState('networkidle');
 await page.getByRole('button',{name:/Alexandra Rivera/}).click();
 await expect(page.locator('select[name="module:jobs"]')).toHaveValue('read');
 await expect(page.getByRole('checkbox',{name:'employee',exact:true})).toBeChecked();
 const violations=(await new AxeBuilder({page}).analyze()).violations.filter(v=>['critical','serious'].includes(v.impact??''));
 expect(violations).toEqual([]);
 await page.getByRole('heading',{name:'People & access',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:test.info().outputPath('people.png'),fullPage:true});
 await page.getByRole('button',{name:'Archive user',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('archived');
 await page.getByRole('combobox',{name:'Profile',exact:true}).selectOption('archived');
 await page.getByRole('button',{name:/Alexandra Rivera/}).click();
 await page.getByRole('button',{name:'Restore user',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('restored');
 await page.getByRole('combobox',{name:'Profile',exact:true}).selectOption('all');
 await expect(page.getByRole('button',{name:/Alexandra Rivera/})).toBeVisible();
 await page.getByRole('button',{name:/Existing Owner/}).click();
 await expect(page.getByRole('button',{name:'Archive user',exact:true})).toHaveCount(0);
 await expect(page.getByText('Owners retain full company access.')).toBeVisible();
});
