import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const person='33333333-3333-3333-3333-333333333333';
for (const mobile of [false,true]) test(`Contact portal access ${mobile?'mobile':'desktop'}: grant, persist, revoke and protect mutations`,async({page,context,request})=>{
 await request.get('http://127.0.0.1:5190/reset');
 await page.setViewportSize(mobile?{width:393,height:851}:{width:1440,height:1000});
 const claims={sub:'11111111-1111-1111-1111-111111111111',role:['owner'],tid:'7d40ea6c-313f-4f53-bf7d-5d1ecb9cc50b',exp:Math.floor(Date.now()/1000)+3600};
 const token=`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.ui-fixture`;
 await context.addCookies([{name:'tko_auth_token',value:token,url:'http://127.0.0.1:5191'}]);
 await page.goto('/bdr/admin/contact?new=1');
 await page.waitForLoadState('networkidle');
 await page.getByLabel('First name',{exact:true}).fill('Portal');
 await page.getByLabel('Last name',{exact:true}).fill('Customer');
 await page.getByLabel('Email',{exact:true}).fill('portal@example.invalid');
 await page.getByLabel('Linked customer record').selectOption('22222222-2222-2222-2222-222222222222');
 await page.getByRole('button',{name:'Save contact',exact:true}).click();
 const panel=page.getByRole('region',{name:'Customer Portal',exact:true});
 await expect(panel.getByText('Status: Inactive',{exact:true})).toBeVisible();
 await panel.getByLabel('Allow portal access',{exact:true}).check();
 await panel.getByRole('combobox',{name:'Access scope',exact:true}).selectOption('job');
 await panel.getByRole('combobox',{name:'Work or site',exact:true}).selectOption({label:'Front entry repair'});
 const expiry=new Date();expiry.setMonth(expiry.getMonth()+3);
 await panel.getByLabel('Access expires',{exact:true}).fill(expiry.toISOString().slice(0,10));
 await panel.getByRole('button',{name:'Grant portal access',exact:true}).click();
 await expect(panel.getByText('Status: Active',{exact:true})).toBeVisible();
 await page.reload();await expect(panel.getByLabel('Allow portal access',{exact:true})).toBeChecked();
 await panel.getByRole('button',{name:'Add access scope',exact:true}).click();
 await panel.getByRole('combobox',{name:'Access scope',exact:true}).selectOption('site');
 await panel.getByRole('combobox',{name:'Work or site',exact:true}).selectOption({label:'Main office'});
 await panel.getByLabel('Access expires',{exact:true}).fill(expiry.toISOString().slice(0,10));
 await panel.getByRole('button',{name:'Grant portal access',exact:true}).click();
 await expect(panel.getByRole('listitem')).toHaveCount(2);
 const endpoint=`/bdr/admin/settings/portal/contacts/${person}`;
 const state=await (await page.request.get(endpoint)).json();
 const stale=await page.request.post(endpoint,{headers:{Origin:'http://127.0.0.1:5191'},data:{action:'disable',version:'stale'}});expect(stale.status()).toBe(409);
 const foreign=await page.request.post(endpoint,{headers:{Origin:'https://other.example'},data:{action:'disable',version:state.version}});expect(foreign.status()).toBe(403);
 expect((await page.request.get(endpoint)).headers()['cache-control']).toContain('no-store');
 await panel.getByLabel('Allow portal access',{exact:true}).click();
 await panel.getByRole('button',{name:'Keep access',exact:true}).click();
 await expect(panel.getByLabel('Allow portal access',{exact:true})).toBeChecked();
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto(`/bdr/admin/users?person=${person}`);
 await expect(panel.getByText('Status: Active',{exact:true})).toBeVisible();
 await panel.getByLabel('Allow portal access',{exact:true}).click();
 await panel.getByRole('button',{name:'Revoke all portal access',exact:true}).click();
 await expect(panel.getByText('Status: Revoked',{exact:true})).toBeVisible();
 await expect(panel.getByLabel('Allow portal access',{exact:true})).not.toBeChecked();
 await page.reload();await expect(panel.getByText('Status: Revoked',{exact:true})).toBeVisible();
 const saved=await (await request.get('http://127.0.0.1:5190/api/people',{headers:{Authorization:`Bearer ${token}`}})).json();
 expect(saved.data.find((p:{id:string})=>p.id===person).role).toBeUndefined();
 const adminToken=`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify({...claims,role:['admin']})).toString('base64url')}.ui-fixture`;
 await context.addCookies([{name:'tko_auth_token',value:adminToken,url:'http://127.0.0.1:5191'}]);
 expect((await page.request.get(endpoint)).status()).toBe(403);
});

for (const mobile of [false,true]) test(`Carl Zipf customer screen exposes linked contact portal access ${mobile?'mobile':'desktop'}`,async({page,context,request})=>{
 await request.get('http://127.0.0.1:5190/reset');
 await page.setViewportSize(mobile?{width:393,height:851}:{width:1440,height:1000});
 const claims={sub:'11111111-1111-1111-1111-111111111111',role:['owner'],tid:'88888888-8888-4888-8888-888888888883',exp:Math.floor(Date.now()/1000)+3600};
 const token=`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.ui-fixture`;
 await context.addCookies([{name:'tko_auth_token',value:token,url:'http://127.0.0.1:5191'}]);
 const customer='22222222-2222-2222-2222-222222222222';
 await page.goto(`/carlzipf/admin/customers?customer=${customer}`);
 await expect(page.getByText('No customer contacts are linked yet.',{exact:false})).toBeVisible();
 await page.getByRole('link',{name:'Add customer contact',exact:true}).click();
 await page.waitForLoadState('networkidle');
 await expect(page.getByRole('main')).toHaveCSS('overflow-y','auto');
 await expect(page.getByLabel('Linked customer record')).toHaveValue(customer);
 await page.getByLabel('First name',{exact:true}).fill('Customer');
 await page.getByLabel('Last name',{exact:true}).fill('Contact');
 await page.getByLabel('Email',{exact:true}).fill('contact@example.invalid');
 await page.getByRole('button',{name:'Save contact',exact:true}).click();
 await expect(page.getByText('Status: Inactive',{exact:true})).toBeVisible();
 await page.goto(`/carlzipf/admin/customers?customer=${customer}`);
 const panel=page.getByRole('region',{name:'Customer Portal',exact:true});
 await expect(panel.getByText('Status: Inactive',{exact:true})).toBeVisible();
 await expect(page.getByRole('combobox',{name:'Customer contact',exact:true})).toHaveValue(person);
 await panel.getByLabel('Allow portal access',{exact:true}).check();
 const expiry=new Date();expiry.setMonth(expiry.getMonth()+3);
 await panel.getByLabel('Access expires',{exact:true}).fill(expiry.toISOString().slice(0,10));
 await panel.getByRole('button',{name:'Grant portal access',exact:true}).click();
 await expect(panel.getByText('Status: Active',{exact:true})).toBeVisible();
 await page.reload();await expect(panel.getByText('Status: Active',{exact:true})).toBeVisible();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
